package com.zhiliao.hotel.mapper;

import com.zhiliao.hotel.model.ZlServiceorder;
import org.apache.ibatis.annotations.Param;

public interface ZlServiceorderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zl_serviceorder
     *
     * @mbg.generated Wed May 20 17:41:35 CST 2020
     */
    int insert(ZlServiceorder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zl_serviceorder
     *
     * @mbg.generated Wed May 20 17:41:35 CST 2020
     */
    int insertSelective(ZlServiceorder record);

    ZlServiceorder getByOrderId(@Param("orderId") Long orderId);
}