package com.zhiliao.hotel.model;

import java.io.Serializable;
import java.util.Date;

/**
 * 
 *   酒店咨讯类
 * @author null
 * @date 2020-04-10
 */
public class SjCbNews implements Serializable {
    /**
     * 主键
     */
    private Integer id;

    /**
     * 酒店id
     */
    private Integer jiudianid;

    /**
     * 作者
     */
    private String author;

    /**
     * 标题
     */
    private String title;

    /**
     * 标题图
     */
    private String turl;

    /**
     * 阅读图
     */
    private Short viewcount;

    /**
     * 排序
     */
    private Short sort;

    /**
     * 简介
     */
    private String desc;

    /**
     * 新闻时间
     */
    private Date newstime;

    /**
     * 内容id
     */
    private Integer contentid;

    /**
     * 是否启用
     */
    private Boolean status;

    /**
     * 添加时间
     */
    private Integer addtime;

    /**
     * 修改时间
     */
    private String adduser;

    /**
     * 添加ip
     */
    private String addip;

    /**
     * 修改时间
     */
    private Integer editime;

    /**
     * 修改人
     */
    private String edituser;

    /**
     * 修改ip
     */
    private String editip;
    /**
     * 酒店名称
     */
    private String jiudianTitle;

    public String getJiudianTitle() {
        return jiudianTitle;
    }

    public void setJiudianTitle(String jiudianTitle) {
        this.jiudianTitle = jiudianTitle;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sj_cb_news
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_cb_news.id
     *
     * @return the value of sj_cb_news.id
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_cb_news.id
     *
     * @param id the value for sj_cb_news.id
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_cb_news.jiudianid
     *
     * @return the value of sj_cb_news.jiudianid
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public Integer getJiudianid() {
        return jiudianid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_cb_news.jiudianid
     *
     * @param jiudianid the value for sj_cb_news.jiudianid
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public void setJiudianid(Integer jiudianid) {
        this.jiudianid = jiudianid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_cb_news.author
     *
     * @return the value of sj_cb_news.author
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_cb_news.author
     *
     * @param author the value for sj_cb_news.author
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_cb_news.title
     *
     * @return the value of sj_cb_news.title
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_cb_news.title
     *
     * @param title the value for sj_cb_news.title
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_cb_news.turl
     *
     * @return the value of sj_cb_news.turl
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public String getTurl() {
        return turl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_cb_news.turl
     *
     * @param turl the value for sj_cb_news.turl
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public void setTurl(String turl) {
        this.turl = turl == null ? null : turl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_cb_news.viewcount
     *
     * @return the value of sj_cb_news.viewcount
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public Short getViewcount() {
        return viewcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_cb_news.viewcount
     *
     * @param viewcount the value for sj_cb_news.viewcount
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public void setViewcount(Short viewcount) {
        this.viewcount = viewcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_cb_news.sort
     *
     * @return the value of sj_cb_news.sort
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public Short getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_cb_news.sort
     *
     * @param sort the value for sj_cb_news.sort
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public void setSort(Short sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_cb_news.desc
     *
     * @return the value of sj_cb_news.desc
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_cb_news.desc
     *
     * @param desc the value for sj_cb_news.desc
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_cb_news.newstime
     *
     * @return the value of sj_cb_news.newstime
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public Date getNewstime() {
        return newstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_cb_news.newstime
     *
     * @param newstime the value for sj_cb_news.newstime
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public void setNewstime(Date newstime) {
        this.newstime = newstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_cb_news.contentid
     *
     * @return the value of sj_cb_news.contentid
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public Integer getContentid() {
        return contentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_cb_news.contentid
     *
     * @param contentid the value for sj_cb_news.contentid
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public void setContentid(Integer contentid) {
        this.contentid = contentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_cb_news.status
     *
     * @return the value of sj_cb_news.status
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_cb_news.status
     *
     * @param status the value for sj_cb_news.status
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_cb_news.addtime
     *
     * @return the value of sj_cb_news.addtime
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public Integer getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_cb_news.addtime
     *
     * @param addtime the value for sj_cb_news.addtime
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public void setAddtime(Integer addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_cb_news.adduser
     *
     * @return the value of sj_cb_news.adduser
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public String getAdduser() {
        return adduser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_cb_news.adduser
     *
     * @param adduser the value for sj_cb_news.adduser
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public void setAdduser(String adduser) {
        this.adduser = adduser == null ? null : adduser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_cb_news.addip
     *
     * @return the value of sj_cb_news.addip
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public String getAddip() {
        return addip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_cb_news.addip
     *
     * @param addip the value for sj_cb_news.addip
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public void setAddip(String addip) {
        this.addip = addip == null ? null : addip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_cb_news.editime
     *
     * @return the value of sj_cb_news.editime
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public Integer getEditime() {
        return editime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_cb_news.editime
     *
     * @param editime the value for sj_cb_news.editime
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public void setEditime(Integer editime) {
        this.editime = editime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_cb_news.edituser
     *
     * @return the value of sj_cb_news.edituser
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public String getEdituser() {
        return edituser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_cb_news.edituser
     *
     * @param edituser the value for sj_cb_news.edituser
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public void setEdituser(String edituser) {
        this.edituser = edituser == null ? null : edituser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sj_cb_news.editip
     *
     * @return the value of sj_cb_news.editip
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public String getEditip() {
        return editip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sj_cb_news.editip
     *
     * @param editip the value for sj_cb_news.editip
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    public void setEditip(String editip) {
        this.editip = editip == null ? null : editip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sj_cb_news
     *
     * @mbg.generated Fri Apr 10 16:41:13 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", jiudianid=").append(jiudianid);
        sb.append(", author=").append(author);
        sb.append(", title=").append(title);
        sb.append(", turl=").append(turl);
        sb.append(", viewcount=").append(viewcount);
        sb.append(", sort=").append(sort);
        sb.append(", desc=").append(desc);
        sb.append(", newstime=").append(newstime);
        sb.append(", contentid=").append(contentid);
        sb.append(", status=").append(status);
        sb.append(", addtime=").append(addtime);
        sb.append(", adduser=").append(adduser);
        sb.append(", addip=").append(addip);
        sb.append(", editime=").append(editime);
        sb.append(", edituser=").append(edituser);
        sb.append(", editip=").append(editip);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append(", jiudianTitle=").append(jiudianTitle);
        sb.append("]");
        return sb.toString();
    }
}