package com.zhiliao.hotel.model;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * 
 *
 * @author null
 * @date 2020-05-20
 */
public class ZlCoupon implements Serializable {
    /**
     * 优惠券ID
     */
    private Integer couponid;

    /**
     * 酒店ID：0平台；其它酒店ID
     */
    private Integer hotelid;

    /**
     * 优惠券名称
     */
    private String couponname;

    /**
     * 优惠券数量
     */
    private Integer couponcount;

    /**
     * 最小金额，满多少金额才能使用
     */
    private BigDecimal minmoney;

    /**
     * 满减的金额
     */
    private BigDecimal discountmoney;

    /**
     * 可领取开始时间
     */
    private Integer fetchbegindate;

    /**
     * 可领取结束时间
     */
    private Integer fetchenddate;

    /**
     * 允许开始使用时间
     */
    private Integer allowbeginusedate;

    /**
     * 允许结束使用时间
     */
    private Integer allowendusedate;

    /**
     * 领取后有效天数
     */
    private Integer validdaycount;

    /**
     * 限定类型：0通用型；1限定类型
     */
    private Byte limitcategorytype;

    /**
     * 0:限定使用天数ValidDayCount；1:限定使用日期AllowBeginUseDate－AllowEndUseDate
     */
    private Byte limitdatetype;

    /**
     * 所属模块 1:客房服务;2便利店;3餐饮服务;4情趣用品;5土特产
     */
    private Short belongmodule;

    /**
     * 0:未启用；1启用
     */
    private Byte couponstatus;

    /**
     * 删除状态:0正常;1删除;
     */
    private Boolean isdelete;

    /**
     * 创建时间
     */
    private Integer createdate;

    /**
     * 修改时间
     */
    private Integer updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zl_coupon
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_coupon.CouponID
     *
     * @return the value of zl_coupon.CouponID
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public Integer getCouponid() {
        return couponid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_coupon.CouponID
     *
     * @param couponid the value for zl_coupon.CouponID
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public void setCouponid(Integer couponid) {
        this.couponid = couponid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_coupon.HotelID
     *
     * @return the value of zl_coupon.HotelID
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public Integer getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_coupon.HotelID
     *
     * @param hotelid the value for zl_coupon.HotelID
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_coupon.CouponName
     *
     * @return the value of zl_coupon.CouponName
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public String getCouponname() {
        return couponname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_coupon.CouponName
     *
     * @param couponname the value for zl_coupon.CouponName
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public void setCouponname(String couponname) {
        this.couponname = couponname == null ? null : couponname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_coupon.CouponCount
     *
     * @return the value of zl_coupon.CouponCount
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public Integer getCouponcount() {
        return couponcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_coupon.CouponCount
     *
     * @param couponcount the value for zl_coupon.CouponCount
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public void setCouponcount(Integer couponcount) {
        this.couponcount = couponcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_coupon.MinMoney
     *
     * @return the value of zl_coupon.MinMoney
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public BigDecimal getMinmoney() {
        return minmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_coupon.MinMoney
     *
     * @param minmoney the value for zl_coupon.MinMoney
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public void setMinmoney(BigDecimal minmoney) {
        this.minmoney = minmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_coupon.DiscountMoney
     *
     * @return the value of zl_coupon.DiscountMoney
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public BigDecimal getDiscountmoney() {
        return discountmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_coupon.DiscountMoney
     *
     * @param discountmoney the value for zl_coupon.DiscountMoney
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public void setDiscountmoney(BigDecimal discountmoney) {
        this.discountmoney = discountmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_coupon.FetchBeginDate
     *
     * @return the value of zl_coupon.FetchBeginDate
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public Integer getFetchbegindate() {
        return fetchbegindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_coupon.FetchBeginDate
     *
     * @param fetchbegindate the value for zl_coupon.FetchBeginDate
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public void setFetchbegindate(Integer fetchbegindate) {
        this.fetchbegindate = fetchbegindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_coupon.FetchEndDate
     *
     * @return the value of zl_coupon.FetchEndDate
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public Integer getFetchenddate() {
        return fetchenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_coupon.FetchEndDate
     *
     * @param fetchenddate the value for zl_coupon.FetchEndDate
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public void setFetchenddate(Integer fetchenddate) {
        this.fetchenddate = fetchenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_coupon.AllowBeginUseDate
     *
     * @return the value of zl_coupon.AllowBeginUseDate
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public Integer getAllowbeginusedate() {
        return allowbeginusedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_coupon.AllowBeginUseDate
     *
     * @param allowbeginusedate the value for zl_coupon.AllowBeginUseDate
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public void setAllowbeginusedate(Integer allowbeginusedate) {
        this.allowbeginusedate = allowbeginusedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_coupon.AllowEndUseDate
     *
     * @return the value of zl_coupon.AllowEndUseDate
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public Integer getAllowendusedate() {
        return allowendusedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_coupon.AllowEndUseDate
     *
     * @param allowendusedate the value for zl_coupon.AllowEndUseDate
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public void setAllowendusedate(Integer allowendusedate) {
        this.allowendusedate = allowendusedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_coupon.ValidDayCount
     *
     * @return the value of zl_coupon.ValidDayCount
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public Integer getValiddaycount() {
        return validdaycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_coupon.ValidDayCount
     *
     * @param validdaycount the value for zl_coupon.ValidDayCount
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public void setValiddaycount(Integer validdaycount) {
        this.validdaycount = validdaycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_coupon.LimitCategoryType
     *
     * @return the value of zl_coupon.LimitCategoryType
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public Byte getLimitcategorytype() {
        return limitcategorytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_coupon.LimitCategoryType
     *
     * @param limitcategorytype the value for zl_coupon.LimitCategoryType
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public void setLimitcategorytype(Byte limitcategorytype) {
        this.limitcategorytype = limitcategorytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_coupon.LimitDateType
     *
     * @return the value of zl_coupon.LimitDateType
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public Byte getLimitdatetype() {
        return limitdatetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_coupon.LimitDateType
     *
     * @param limitdatetype the value for zl_coupon.LimitDateType
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public void setLimitdatetype(Byte limitdatetype) {
        this.limitdatetype = limitdatetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_coupon.BelongModule
     *
     * @return the value of zl_coupon.BelongModule
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public Short getBelongmodule() {
        return belongmodule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_coupon.BelongModule
     *
     * @param belongmodule the value for zl_coupon.BelongModule
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public void setBelongmodule(Short belongmodule) {
        this.belongmodule = belongmodule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_coupon.CouponStatus
     *
     * @return the value of zl_coupon.CouponStatus
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public Byte getCouponstatus() {
        return couponstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_coupon.CouponStatus
     *
     * @param couponstatus the value for zl_coupon.CouponStatus
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public void setCouponstatus(Byte couponstatus) {
        this.couponstatus = couponstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_coupon.IsDelete
     *
     * @return the value of zl_coupon.IsDelete
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_coupon.IsDelete
     *
     * @param isdelete the value for zl_coupon.IsDelete
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_coupon.Createdate
     *
     * @return the value of zl_coupon.Createdate
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public Integer getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_coupon.Createdate
     *
     * @param createdate the value for zl_coupon.Createdate
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public void setCreatedate(Integer createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_coupon.UpdateDate
     *
     * @return the value of zl_coupon.UpdateDate
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public Integer getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_coupon.UpdateDate
     *
     * @param updatedate the value for zl_coupon.UpdateDate
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    public void setUpdatedate(Integer updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zl_coupon
     *
     * @mbg.generated Wed May 20 15:26:59 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", couponid=").append(couponid);
        sb.append(", hotelid=").append(hotelid);
        sb.append(", couponname=").append(couponname);
        sb.append(", couponcount=").append(couponcount);
        sb.append(", minmoney=").append(minmoney);
        sb.append(", discountmoney=").append(discountmoney);
        sb.append(", fetchbegindate=").append(fetchbegindate);
        sb.append(", fetchenddate=").append(fetchenddate);
        sb.append(", allowbeginusedate=").append(allowbeginusedate);
        sb.append(", allowendusedate=").append(allowendusedate);
        sb.append(", validdaycount=").append(validdaycount);
        sb.append(", limitcategorytype=").append(limitcategorytype);
        sb.append(", limitdatetype=").append(limitdatetype);
        sb.append(", belongmodule=").append(belongmodule);
        sb.append(", couponstatus=").append(couponstatus);
        sb.append(", isdelete=").append(isdelete);
        sb.append(", createdate=").append(createdate);
        sb.append(", updatedate=").append(updatedate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}