package com.zhiliao.hotel.model;

import java.io.Serializable;

/**
 * 
 *
 * @author null
 * @date 2020-05-27
 */
public class ZlDisburdeneatlive implements Serializable {
    /**
     * 自增ID
     */
    private Integer recid;

    /**
     * 酒店ID
     */
    private Integer hotelid;

    /**
     * 住户情况统计最小值
     */
    private Integer randomminval;

    /**
     * 住户情况统计最大值
     */
    private Integer randommaxval;

    /**
     * 修改时间
     */
    private Integer updatedate;

    /**
     * 用户ID
     */
    private Integer adminid;

    /**
     * 操作人员(审核人员)
     */
    private String operatorusername;

    /**
     * 作者
     */
    private String adminname;

    /**
     * 操作人员IP
     */
    private String operatorip;

    /**
     * 操作备注(审核备注)
     */
    private String operatorremark;

    /**
     * 上下架状态:0:下架;1上架
     */
    private Byte eatlivestatus;

    /**
     * 审核状态:-1驳回;0待审核;1审核中;2审核通过0:下架;1上架
     */
    private Byte checkstatus;

    /**
     * 阅读数
     */
    private Integer visitcount;

    /**
     * 删除状态:0正常;1删除;
     */
    private Boolean isdelete;

    /**
     * 添加时间
     */
    private Integer createdate;

    /**
     * 清扫情况
     */
    private String cleansituation;

    /**
     * 布草情况
     */
    private String setupsituation;

    /**
     * 食品安全
     */
    private String goodssituation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zl_disburdeneatlive
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_disburdeneatlive.RecID
     *
     * @return the value of zl_disburdeneatlive.RecID
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public Integer getRecid() {
        return recid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_disburdeneatlive.RecID
     *
     * @param recid the value for zl_disburdeneatlive.RecID
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public void setRecid(Integer recid) {
        this.recid = recid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_disburdeneatlive.HotelID
     *
     * @return the value of zl_disburdeneatlive.HotelID
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public Integer getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_disburdeneatlive.HotelID
     *
     * @param hotelid the value for zl_disburdeneatlive.HotelID
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_disburdeneatlive.RandomMinVal
     *
     * @return the value of zl_disburdeneatlive.RandomMinVal
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public Integer getRandomminval() {
        return randomminval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_disburdeneatlive.RandomMinVal
     *
     * @param randomminval the value for zl_disburdeneatlive.RandomMinVal
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public void setRandomminval(Integer randomminval) {
        this.randomminval = randomminval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_disburdeneatlive.RandomMaxVal
     *
     * @return the value of zl_disburdeneatlive.RandomMaxVal
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public Integer getRandommaxval() {
        return randommaxval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_disburdeneatlive.RandomMaxVal
     *
     * @param randommaxval the value for zl_disburdeneatlive.RandomMaxVal
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public void setRandommaxval(Integer randommaxval) {
        this.randommaxval = randommaxval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_disburdeneatlive.UpdateDate
     *
     * @return the value of zl_disburdeneatlive.UpdateDate
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public Integer getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_disburdeneatlive.UpdateDate
     *
     * @param updatedate the value for zl_disburdeneatlive.UpdateDate
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public void setUpdatedate(Integer updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_disburdeneatlive.AdminID
     *
     * @return the value of zl_disburdeneatlive.AdminID
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public Integer getAdminid() {
        return adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_disburdeneatlive.AdminID
     *
     * @param adminid the value for zl_disburdeneatlive.AdminID
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public void setAdminid(Integer adminid) {
        this.adminid = adminid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_disburdeneatlive.OperatorUserName
     *
     * @return the value of zl_disburdeneatlive.OperatorUserName
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public String getOperatorusername() {
        return operatorusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_disburdeneatlive.OperatorUserName
     *
     * @param operatorusername the value for zl_disburdeneatlive.OperatorUserName
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public void setOperatorusername(String operatorusername) {
        this.operatorusername = operatorusername == null ? null : operatorusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_disburdeneatlive.AdminName
     *
     * @return the value of zl_disburdeneatlive.AdminName
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public String getAdminname() {
        return adminname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_disburdeneatlive.AdminName
     *
     * @param adminname the value for zl_disburdeneatlive.AdminName
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public void setAdminname(String adminname) {
        this.adminname = adminname == null ? null : adminname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_disburdeneatlive.OperatorIP
     *
     * @return the value of zl_disburdeneatlive.OperatorIP
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public String getOperatorip() {
        return operatorip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_disburdeneatlive.OperatorIP
     *
     * @param operatorip the value for zl_disburdeneatlive.OperatorIP
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public void setOperatorip(String operatorip) {
        this.operatorip = operatorip == null ? null : operatorip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_disburdeneatlive.OperatorRemark
     *
     * @return the value of zl_disburdeneatlive.OperatorRemark
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public String getOperatorremark() {
        return operatorremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_disburdeneatlive.OperatorRemark
     *
     * @param operatorremark the value for zl_disburdeneatlive.OperatorRemark
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public void setOperatorremark(String operatorremark) {
        this.operatorremark = operatorremark == null ? null : operatorremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_disburdeneatlive.EatLiveStatus
     *
     * @return the value of zl_disburdeneatlive.EatLiveStatus
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public Byte getEatlivestatus() {
        return eatlivestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_disburdeneatlive.EatLiveStatus
     *
     * @param eatlivestatus the value for zl_disburdeneatlive.EatLiveStatus
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public void setEatlivestatus(Byte eatlivestatus) {
        this.eatlivestatus = eatlivestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_disburdeneatlive.CheckStatus
     *
     * @return the value of zl_disburdeneatlive.CheckStatus
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public Byte getCheckstatus() {
        return checkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_disburdeneatlive.CheckStatus
     *
     * @param checkstatus the value for zl_disburdeneatlive.CheckStatus
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public void setCheckstatus(Byte checkstatus) {
        this.checkstatus = checkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_disburdeneatlive.VisitCount
     *
     * @return the value of zl_disburdeneatlive.VisitCount
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public Integer getVisitcount() {
        return visitcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_disburdeneatlive.VisitCount
     *
     * @param visitcount the value for zl_disburdeneatlive.VisitCount
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public void setVisitcount(Integer visitcount) {
        this.visitcount = visitcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_disburdeneatlive.IsDelete
     *
     * @return the value of zl_disburdeneatlive.IsDelete
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_disburdeneatlive.IsDelete
     *
     * @param isdelete the value for zl_disburdeneatlive.IsDelete
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_disburdeneatlive.CreateDate
     *
     * @return the value of zl_disburdeneatlive.CreateDate
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public Integer getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_disburdeneatlive.CreateDate
     *
     * @param createdate the value for zl_disburdeneatlive.CreateDate
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public void setCreatedate(Integer createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_disburdeneatlive.CleanSituation
     *
     * @return the value of zl_disburdeneatlive.CleanSituation
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public String getCleansituation() {
        return cleansituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_disburdeneatlive.CleanSituation
     *
     * @param cleansituation the value for zl_disburdeneatlive.CleanSituation
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public void setCleansituation(String cleansituation) {
        this.cleansituation = cleansituation == null ? null : cleansituation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_disburdeneatlive.SetupSituation
     *
     * @return the value of zl_disburdeneatlive.SetupSituation
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public String getSetupsituation() {
        return setupsituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_disburdeneatlive.SetupSituation
     *
     * @param setupsituation the value for zl_disburdeneatlive.SetupSituation
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public void setSetupsituation(String setupsituation) {
        this.setupsituation = setupsituation == null ? null : setupsituation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_disburdeneatlive.GoodsSituation
     *
     * @return the value of zl_disburdeneatlive.GoodsSituation
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public String getGoodssituation() {
        return goodssituation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_disburdeneatlive.GoodsSituation
     *
     * @param goodssituation the value for zl_disburdeneatlive.GoodsSituation
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    public void setGoodssituation(String goodssituation) {
        this.goodssituation = goodssituation == null ? null : goodssituation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zl_disburdeneatlive
     *
     * @mbg.generated Wed May 27 10:11:56 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", recid=").append(recid);
        sb.append(", hotelid=").append(hotelid);
        sb.append(", randomminval=").append(randomminval);
        sb.append(", randommaxval=").append(randommaxval);
        sb.append(", updatedate=").append(updatedate);
        sb.append(", adminid=").append(adminid);
        sb.append(", operatorusername=").append(operatorusername);
        sb.append(", adminname=").append(adminname);
        sb.append(", operatorip=").append(operatorip);
        sb.append(", operatorremark=").append(operatorremark);
        sb.append(", eatlivestatus=").append(eatlivestatus);
        sb.append(", checkstatus=").append(checkstatus);
        sb.append(", visitcount=").append(visitcount);
        sb.append(", isdelete=").append(isdelete);
        sb.append(", createdate=").append(createdate);
        sb.append(", cleansituation=").append(cleansituation);
        sb.append(", setupsituation=").append(setupsituation);
        sb.append(", goodssituation=").append(goodssituation);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}