package com.zhiliao.hotel.model;

import java.io.Serializable;

/**
 * 商品表
 *
 * @author xiehuiyi
 * @date 2020-04-15
 */
public class ZlGoods implements Serializable {
    /**
     * 商品ID
     */
    private Integer goodsid;

    /**
     * 酒店ID
     */
    private Integer hotelid;

    /**
     * 所属分类ID
     */
    private Integer goodscategoryid;

    /**
     * 供应商ID
     */
    private Integer supplierid;

    /**
     * 商品封面图片
     */
    private String coverimgurl;

    /**
     * 商品名称
     */
    private String goodsname;

    /**
     * 商品详情
     */
    private String content;

    /**
     * 0:不需要配送;1需要配送(土特产)
     */
    private Boolean needdelivery;

    /**
     * 是否推荐:0:否;1:是
     */
    private Boolean isrecommand;

    /**
     * 0:下架;1上架
     */
    private Byte goodsstatus;

    /**
     * 排序
     */
    private Integer sort;

    /**
     * 删除状态:0正常;1删除;
     */
    private Boolean isdelete;

    /**
     * 添加时间
     */
    private Integer createdate;

    /**
     * 修改时间
     */
    private Integer updatedate;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zl_goods
     *
     * @mbg.generated Wed Apr 15 10:13:19 SGT 2020
     */
    private static final long serialVersionUID = 1L;

    public Integer getGoodsid() {
        return goodsid;
    }

    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    public Integer getHotelid() {
        return hotelid;
    }

    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    public Integer getGoodscategoryid() {
        return goodscategoryid;
    }

    public void setGoodscategoryid(Integer goodscategoryid) {
        this.goodscategoryid = goodscategoryid;
    }

    public Integer getSupplierid() {
        return supplierid;
    }

    public void setSupplierid(Integer supplierid) {
        this.supplierid = supplierid;
    }

    public String getCoverimgurl() {
        return coverimgurl;
    }

    public void setCoverimgurl(String coverimgurl) {
        this.coverimgurl = coverimgurl;
    }

    public String getGoodsname() {
        return goodsname;
    }

    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Boolean getNeeddelivery() {
        return needdelivery;
    }

    public void setNeeddelivery(Boolean needdelivery) {
        this.needdelivery = needdelivery;
    }

    public Boolean getIsrecommand() {
        return isrecommand;
    }

    public void setIsrecommand(Boolean isrecommand) {
        this.isrecommand = isrecommand;
    }

    public Byte getGoodsstatus() {
        return goodsstatus;
    }

    public void setGoodsstatus(Byte goodsstatus) {
        this.goodsstatus = goodsstatus;
    }

    public Integer getSort() {
        return sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    public Boolean getIsdelete() {
        return isdelete;
    }

    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    public Integer getCreatedate() {
        return createdate;
    }

    public void setCreatedate(Integer createdate) {
        this.createdate = createdate;
    }

    public Integer getUpdatedate() {
        return updatedate;
    }

    public void setUpdatedate(Integer updatedate) {
        this.updatedate = updatedate;
    }
}