package com.zhiliao.hotel.model;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * 房型信息
 *
 * @author denghanchen
 * @date 2020-04-14
 */
public class ZlHotelroomtype implements Serializable {
    /**
     * 
     */
    private Integer roomtypeid;

    /**
     * 房型
     */
    private String roomtypename;

    /**
     * 介绍
     */
    private String description;

    /**
     * 酒店ID
     */
    private Integer hotelid;

    /**
     * 浏览人数
     */
    private Integer visitcount;

    /**
     * 现价
     */
    private BigDecimal currentprice;

    /**
     * 原价
     */
    private BigDecimal originalprice;

    /**
     * 图片
     */
    private String banner;

    /**
     * 标签组(与tags表对应);多个用|隔开
     */
    private String tagids;

    /**
     * 房间大小
     */
    private String roomsize;

    /**
     * 适合居住人数
     */
    private Byte customercount;

    /**
     * 房间大小
     */
    private String bedsize;

    /**
     * 排序
     */
    private Byte sort;

    /**
     * 状态
     */
    private Byte status;

    /**
     * 删除状态:0正常;1删除;
     */
    private String isdelete;

    /**
     * 
     */
    private Integer createdate;

    /**
     * 
     */
    private Integer updatedate;

    /**
     * 价格组
     */
    private String rankmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zl_hotelroomtype
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelroomtype.RoomTypeID
     *
     * @return the value of zl_hotelroomtype.RoomTypeID
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public Integer getRoomtypeid() {
        return roomtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelroomtype.RoomTypeID
     *
     * @param roomtypeid the value for zl_hotelroomtype.RoomTypeID
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public void setRoomtypeid(Integer roomtypeid) {
        this.roomtypeid = roomtypeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelroomtype.RoomTypeName
     *
     * @return the value of zl_hotelroomtype.RoomTypeName
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public String getRoomtypename() {
        return roomtypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelroomtype.RoomTypeName
     *
     * @param roomtypename the value for zl_hotelroomtype.RoomTypeName
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public void setRoomtypename(String roomtypename) {
        this.roomtypename = roomtypename == null ? null : roomtypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelroomtype.Description
     *
     * @return the value of zl_hotelroomtype.Description
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelroomtype.Description
     *
     * @param description the value for zl_hotelroomtype.Description
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelroomtype.HotelID
     *
     * @return the value of zl_hotelroomtype.HotelID
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public Integer getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelroomtype.HotelID
     *
     * @param hotelid the value for zl_hotelroomtype.HotelID
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelroomtype.VisitCount
     *
     * @return the value of zl_hotelroomtype.VisitCount
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public Integer getVisitcount() {
        return visitcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelroomtype.VisitCount
     *
     * @param visitcount the value for zl_hotelroomtype.VisitCount
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public void setVisitcount(Integer visitcount) {
        this.visitcount = visitcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelroomtype.CurrentPrice
     *
     * @return the value of zl_hotelroomtype.CurrentPrice
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public BigDecimal getCurrentprice() {
        return currentprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelroomtype.CurrentPrice
     *
     * @param currentprice the value for zl_hotelroomtype.CurrentPrice
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public void setCurrentprice(BigDecimal currentprice) {
        this.currentprice = currentprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelroomtype.OriginalPrice
     *
     * @return the value of zl_hotelroomtype.OriginalPrice
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public BigDecimal getOriginalprice() {
        return originalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelroomtype.OriginalPrice
     *
     * @param originalprice the value for zl_hotelroomtype.OriginalPrice
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public void setOriginalprice(BigDecimal originalprice) {
        this.originalprice = originalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelroomtype.Banner
     *
     * @return the value of zl_hotelroomtype.Banner
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public String getBanner() {
        return banner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelroomtype.Banner
     *
     * @param banner the value for zl_hotelroomtype.Banner
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public void setBanner(String banner) {
        this.banner = banner == null ? null : banner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelroomtype.TagIDs
     *
     * @return the value of zl_hotelroomtype.TagIDs
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public String getTagids() {
        return tagids;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelroomtype.TagIDs
     *
     * @param tagids the value for zl_hotelroomtype.TagIDs
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public void setTagids(String tagids) {
        this.tagids = tagids == null ? null : tagids.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelroomtype.RoomSize
     *
     * @return the value of zl_hotelroomtype.RoomSize
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public String getRoomsize() {
        return roomsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelroomtype.RoomSize
     *
     * @param roomsize the value for zl_hotelroomtype.RoomSize
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public void setRoomsize(String roomsize) {
        this.roomsize = roomsize == null ? null : roomsize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelroomtype.CustomerCount
     *
     * @return the value of zl_hotelroomtype.CustomerCount
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public Byte getCustomercount() {
        return customercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelroomtype.CustomerCount
     *
     * @param customercount the value for zl_hotelroomtype.CustomerCount
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public void setCustomercount(Byte customercount) {
        this.customercount = customercount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelroomtype.BedSize
     *
     * @return the value of zl_hotelroomtype.BedSize
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public String getBedsize() {
        return bedsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelroomtype.BedSize
     *
     * @param bedsize the value for zl_hotelroomtype.BedSize
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public void setBedsize(String bedsize) {
        this.bedsize = bedsize == null ? null : bedsize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelroomtype.Sort
     *
     * @return the value of zl_hotelroomtype.Sort
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public Byte getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelroomtype.Sort
     *
     * @param sort the value for zl_hotelroomtype.Sort
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public void setSort(Byte sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelroomtype.Status
     *
     * @return the value of zl_hotelroomtype.Status
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelroomtype.Status
     *
     * @param status the value for zl_hotelroomtype.Status
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelroomtype.IsDelete
     *
     * @return the value of zl_hotelroomtype.IsDelete
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public String getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelroomtype.IsDelete
     *
     * @param isdelete the value for zl_hotelroomtype.IsDelete
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public void setIsdelete(String isdelete) {
        this.isdelete = isdelete == null ? null : isdelete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelroomtype.CreateDate
     *
     * @return the value of zl_hotelroomtype.CreateDate
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public Integer getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelroomtype.CreateDate
     *
     * @param createdate the value for zl_hotelroomtype.CreateDate
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public void setCreatedate(Integer createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelroomtype.UpdateDate
     *
     * @return the value of zl_hotelroomtype.UpdateDate
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public Integer getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelroomtype.UpdateDate
     *
     * @param updatedate the value for zl_hotelroomtype.UpdateDate
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public void setUpdatedate(Integer updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelroomtype.Rankmoney
     *
     * @return the value of zl_hotelroomtype.Rankmoney
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public String getRankmoney() {
        return rankmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelroomtype.Rankmoney
     *
     * @param rankmoney the value for zl_hotelroomtype.Rankmoney
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    public void setRankmoney(String rankmoney) {
        this.rankmoney = rankmoney == null ? null : rankmoney.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zl_hotelroomtype
     *
     * @mbg.generated Tue Apr 14 11:25:54 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roomtypeid=").append(roomtypeid);
        sb.append(", roomtypename=").append(roomtypename);
        sb.append(", description=").append(description);
        sb.append(", hotelid=").append(hotelid);
        sb.append(", visitcount=").append(visitcount);
        sb.append(", currentprice=").append(currentprice);
        sb.append(", originalprice=").append(originalprice);
        sb.append(", banner=").append(banner);
        sb.append(", tagids=").append(tagids);
        sb.append(", roomsize=").append(roomsize);
        sb.append(", customercount=").append(customercount);
        sb.append(", bedsize=").append(bedsize);
        sb.append(", sort=").append(sort);
        sb.append(", status=").append(status);
        sb.append(", isdelete=").append(isdelete);
        sb.append(", createdate=").append(createdate);
        sb.append(", updatedate=").append(updatedate);
        sb.append(", rankmoney=").append(rankmoney);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}