package com.zhiliao.hotel.model;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * 酒店信息
 *
 * @author denghanchen
 * @date 2020-04-14
 */
public class ZlHotel implements Serializable {
    /**
     *  酒店ID
     */
    private Integer hotelid;

    /**
     * 酒店名称
     */
    private String hotelname;

    /**
     * 
     */
    private String coverurl;

    /**
     * 客服电话, 多个用|隔开
     */
    private String tel;

    /**
     * 省编号(对应area表AreaID)
     */
    private Short provincecode;

    /**
     * 市编号(对应area表)
     */
    private Short citycode;

    /**
     * 区编号(对应area表)
     */
    private Short districtcode;

    /**
     * 酒店详细地址
     */
    private String address;

    /**
     * 最大允许挂账金额
     */
    private BigDecimal maxcreditcash;

    /**
     * 类型:1酒店;2民宿
     */
    private Byte hoteltype;

    /**
     * 酒店状态:0关闭;1启用
     */
    private Boolean hotelstatus;

    /**
     * 经度
     */
    private Float longitude;

    /**
     * 纬度
     */
    private Float latitude;

    /**
     * 结算方式 百分比
     */
    private Float settlement;

    /**
     * 起送金额
     */
    private Long minsendcash;

    /**
     * 配送金额
     */
    private Long sendcash;

    /**
     * 合约图片,存储多个
     */
    private String contractimgurls;

    /**
     * 开户行
     */
    private String bank;

    /**
     * 开户行账号
     */
    private String bankaccountnumber;

    /**
     * 户名
     */
    private String bankaccountname;

    /**
     * 今天的利润
     */
    private BigDecimal todaymoney;

    /**
     * 总可提现的利润
     */
    private BigDecimal allmoney;

    /**
     * 天气设置
     */
    private String weather;

    /**
     * 是否是S2入驻，0不是，其他S2ID
     */
    private Integer isjoins2;

    /**
     * 删除状态:0正常;1删除;
     */
    private Boolean isdelete;

    /**
     * 更新日期
     */
    private Integer updatedate;

    /**
     * 添加日期
     */
    private Integer createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zl_hotel
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.HotelID
     *
     * @return the value of zl_hotel.HotelID
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public Integer getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.HotelID
     *
     * @param hotelid the value for zl_hotel.HotelID
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.HotelName
     *
     * @return the value of zl_hotel.HotelName
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public String getHotelname() {
        return hotelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.HotelName
     *
     * @param hotelname the value for zl_hotel.HotelName
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setHotelname(String hotelname) {
        this.hotelname = hotelname == null ? null : hotelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.CoverUrl
     *
     * @return the value of zl_hotel.CoverUrl
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public String getCoverurl() {
        return coverurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.CoverUrl
     *
     * @param coverurl the value for zl_hotel.CoverUrl
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setCoverurl(String coverurl) {
        this.coverurl = coverurl == null ? null : coverurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.Tel
     *
     * @return the value of zl_hotel.Tel
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.Tel
     *
     * @param tel the value for zl_hotel.Tel
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.ProvinceCode
     *
     * @return the value of zl_hotel.ProvinceCode
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public Short getProvincecode() {
        return provincecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.ProvinceCode
     *
     * @param provincecode the value for zl_hotel.ProvinceCode
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setProvincecode(Short provincecode) {
        this.provincecode = provincecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.CityCode
     *
     * @return the value of zl_hotel.CityCode
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public Short getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.CityCode
     *
     * @param citycode the value for zl_hotel.CityCode
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setCitycode(Short citycode) {
        this.citycode = citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.DistrictCode
     *
     * @return the value of zl_hotel.DistrictCode
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public Short getDistrictcode() {
        return districtcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.DistrictCode
     *
     * @param districtcode the value for zl_hotel.DistrictCode
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setDistrictcode(Short districtcode) {
        this.districtcode = districtcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.Address
     *
     * @return the value of zl_hotel.Address
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.Address
     *
     * @param address the value for zl_hotel.Address
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.MaxCreditCash
     *
     * @return the value of zl_hotel.MaxCreditCash
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public BigDecimal getMaxcreditcash() {
        return maxcreditcash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.MaxCreditCash
     *
     * @param maxcreditcash the value for zl_hotel.MaxCreditCash
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setMaxcreditcash(BigDecimal maxcreditcash) {
        this.maxcreditcash = maxcreditcash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.HotelType
     *
     * @return the value of zl_hotel.HotelType
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public Byte getHoteltype() {
        return hoteltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.HotelType
     *
     * @param hoteltype the value for zl_hotel.HotelType
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setHoteltype(Byte hoteltype) {
        this.hoteltype = hoteltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.HotelStatus
     *
     * @return the value of zl_hotel.HotelStatus
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public Boolean getHotelstatus() {
        return hotelstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.HotelStatus
     *
     * @param hotelstatus the value for zl_hotel.HotelStatus
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setHotelstatus(Boolean hotelstatus) {
        this.hotelstatus = hotelstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.Longitude
     *
     * @return the value of zl_hotel.Longitude
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.Longitude
     *
     * @param longitude the value for zl_hotel.Longitude
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.Latitude
     *
     * @return the value of zl_hotel.Latitude
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.Latitude
     *
     * @param latitude the value for zl_hotel.Latitude
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.Settlement
     *
     * @return the value of zl_hotel.Settlement
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public Float getSettlement() {
        return settlement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.Settlement
     *
     * @param settlement the value for zl_hotel.Settlement
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setSettlement(Float settlement) {
        this.settlement = settlement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.MinSendCash
     *
     * @return the value of zl_hotel.MinSendCash
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public Long getMinsendcash() {
        return minsendcash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.MinSendCash
     *
     * @param minsendcash the value for zl_hotel.MinSendCash
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setMinsendcash(Long minsendcash) {
        this.minsendcash = minsendcash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.SendCash
     *
     * @return the value of zl_hotel.SendCash
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public Long getSendcash() {
        return sendcash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.SendCash
     *
     * @param sendcash the value for zl_hotel.SendCash
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setSendcash(Long sendcash) {
        this.sendcash = sendcash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.ContractImgUrls
     *
     * @return the value of zl_hotel.ContractImgUrls
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public String getContractimgurls() {
        return contractimgurls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.ContractImgUrls
     *
     * @param contractimgurls the value for zl_hotel.ContractImgUrls
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setContractimgurls(String contractimgurls) {
        this.contractimgurls = contractimgurls == null ? null : contractimgurls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.Bank
     *
     * @return the value of zl_hotel.Bank
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.Bank
     *
     * @param bank the value for zl_hotel.Bank
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.BankAccountNumber
     *
     * @return the value of zl_hotel.BankAccountNumber
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public String getBankaccountnumber() {
        return bankaccountnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.BankAccountNumber
     *
     * @param bankaccountnumber the value for zl_hotel.BankAccountNumber
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setBankaccountnumber(String bankaccountnumber) {
        this.bankaccountnumber = bankaccountnumber == null ? null : bankaccountnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.BankAccountName
     *
     * @return the value of zl_hotel.BankAccountName
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public String getBankaccountname() {
        return bankaccountname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.BankAccountName
     *
     * @param bankaccountname the value for zl_hotel.BankAccountName
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setBankaccountname(String bankaccountname) {
        this.bankaccountname = bankaccountname == null ? null : bankaccountname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.TodayMoney
     *
     * @return the value of zl_hotel.TodayMoney
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public BigDecimal getTodaymoney() {
        return todaymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.TodayMoney
     *
     * @param todaymoney the value for zl_hotel.TodayMoney
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setTodaymoney(BigDecimal todaymoney) {
        this.todaymoney = todaymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.AllMoney
     *
     * @return the value of zl_hotel.AllMoney
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public BigDecimal getAllmoney() {
        return allmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.AllMoney
     *
     * @param allmoney the value for zl_hotel.AllMoney
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setAllmoney(BigDecimal allmoney) {
        this.allmoney = allmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.Weather
     *
     * @return the value of zl_hotel.Weather
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public String getWeather() {
        return weather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.Weather
     *
     * @param weather the value for zl_hotel.Weather
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setWeather(String weather) {
        this.weather = weather == null ? null : weather.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.IsJoinS2
     *
     * @return the value of zl_hotel.IsJoinS2
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public Integer getIsjoins2() {
        return isjoins2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.IsJoinS2
     *
     * @param isjoins2 the value for zl_hotel.IsJoinS2
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setIsjoins2(Integer isjoins2) {
        this.isjoins2 = isjoins2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.IsDelete
     *
     * @return the value of zl_hotel.IsDelete
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.IsDelete
     *
     * @param isdelete the value for zl_hotel.IsDelete
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.UpdateDate
     *
     * @return the value of zl_hotel.UpdateDate
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public Integer getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.UpdateDate
     *
     * @param updatedate the value for zl_hotel.UpdateDate
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setUpdatedate(Integer updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.CreateDate
     *
     * @return the value of zl_hotel.CreateDate
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public Integer getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotel.CreateDate
     *
     * @param createdate the value for zl_hotel.CreateDate
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    public void setCreatedate(Integer createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zl_hotel
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", hotelid=").append(hotelid);
        sb.append(", hotelname=").append(hotelname);
        sb.append(", coverurl=").append(coverurl);
        sb.append(", tel=").append(tel);
        sb.append(", provincecode=").append(provincecode);
        sb.append(", citycode=").append(citycode);
        sb.append(", districtcode=").append(districtcode);
        sb.append(", address=").append(address);
        sb.append(", maxcreditcash=").append(maxcreditcash);
        sb.append(", hoteltype=").append(hoteltype);
        sb.append(", hotelstatus=").append(hotelstatus);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append(", settlement=").append(settlement);
        sb.append(", minsendcash=").append(minsendcash);
        sb.append(", sendcash=").append(sendcash);
        sb.append(", contractimgurls=").append(contractimgurls);
        sb.append(", bank=").append(bank);
        sb.append(", bankaccountnumber=").append(bankaccountnumber);
        sb.append(", bankaccountname=").append(bankaccountname);
        sb.append(", todaymoney=").append(todaymoney);
        sb.append(", allmoney=").append(allmoney);
        sb.append(", weather=").append(weather);
        sb.append(", isjoins2=").append(isjoins2);
        sb.append(", isdelete=").append(isdelete);
        sb.append(", updatedate=").append(updatedate);
        sb.append(", createdate=").append(createdate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}