package com.zhiliao.hotel.model;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * 酒店信息
 *
 * @author denghanchen
 * @date 2020-04-14
 */
public class ZlHotel implements Serializable {
    /**
     *  酒店ID
     */
    private Integer hotelID;

    /**
     * 酒店名称
     */
    private String hotelName;

    /**
     * JoinType=1表示用户ID，2：表示s2合伙人ID
     */
    private Integer extID;

    /**
     * 前台电话(只有一个电话)
     */
    private String receptionTel;

    /**
     * 酒店简称
     */
    private String hotelNameAbbr;

    /**
     * 酒店核对人电话(也是联系人电话)
     */
    private String mobilePhone;

    /**
     * 联系人
     */
    private String contactName;

    /**
     * 最大允许挂账金额
     */
    private BigDecimal maxCreditMoney;

    /**
     * 终止合作时间
     */
    private Integer terminateDate;

    /**
     * 下架时间
     */
    private Integer pullOffDate;

    /**
     * 酒店图片
     */
    private String coverUrl;

    /**
     * 客服电话, 多个用|隔开
     */
    private String tel;

    /**
     * 酒店详细地址
     */
    private String address;


    /**
     * 类型:1酒店;2民宿
     */
    private Byte hotelType;

    /**
     * 酒店状态:0关闭;1启用
     */
    private Boolean hotelStatus;

    /**
     * 今天的利润
     */
    private BigDecimal todayMoney;
    /**
     * 累计获得佣金
     */
    private BigDecimal allMoney;

    /**
     * 已提现佣金
     */
    private BigDecimal withdrewMoney;
    /**
     * 提现处理中佣金
     */
    private BigDecimal withdrawingMoney;

    /**
     * 入驻类型：0：非入驻型；1：酒店自己入驻；2：通过S2入驻
     */
    private Integer joinType;

    /**
     * 入驻酒店合作状态：-1终止合作;1已正常入驻
     */
    private Integer joinStatus;


    /**
     * 所属入驻的用户、合伙人
     */
    private String joinUserName;


    /**
     * 删除状态:0正常;1删除;
     */
    private Boolean isDelete;

    /**
     * 更新日期
     */
    private Integer updateDate;

    /**
     * 添加日期
     */
    private Integer createDate;


    /**
     * 加入时间
     */
    private Integer joinDate;



    public Integer getJoinDate() {
        return joinDate;
    }

    public String getHotelNameAbbr() {
        return hotelNameAbbr;
    }

    public void setHotelNameAbbr(String hotelNameAbbr) {
        this.hotelNameAbbr = hotelNameAbbr;
    }

    public void setJoinDate(Integer joinDate) {
        this.joinDate = joinDate;
    }
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zl_hotel
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    private static final long serialVersionUID = 1L;

    public Integer getHotelID() {
        return hotelID;
    }

    public void setHotelID(Integer hotelID) {
        this.hotelID = hotelID;
    }

    public String getHotelName() {
        return hotelName;
    }

    public void setHotelName(String hotelName) {
        this.hotelName = hotelName;
    }

    public String getCoverUrl() {
        return coverUrl;
    }

    public void setCoverUrl(String coverUrl) {
        this.coverUrl = coverUrl;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getJoinUserName() {
        return joinUserName;
    }

    public void setJoinUserName(String joinUserName) {
        this.joinUserName = joinUserName;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Byte getHotelType() {
        return hotelType;
    }

    public void setHotelType(Byte hotelType) {
        this.hotelType = hotelType;
    }

    public Boolean getHotelStatus() {
        return hotelStatus;
    }

    public void setHotelStatus(Boolean hotelStatus) {
        this.hotelStatus = hotelStatus;
    }

    public BigDecimal getTodayMoney() {
        return todayMoney;
    }

    public void setTodayMoney(BigDecimal todayMoney) {
        this.todayMoney = todayMoney;
    }

    public BigDecimal getAllMoney() {
        return allMoney;
    }

    public void setAllMoney(BigDecimal allMoney) {
        this.allMoney = allMoney;
    }

    public BigDecimal getWithdrewMoney() {
        return withdrewMoney;
    }

    public void setWithdrewMoney(BigDecimal withdrewMoney) {
        this.withdrewMoney = withdrewMoney;
    }

    public BigDecimal getWithdrawingMoney() {
        return withdrawingMoney;
    }

    public void setWithdrawingMoney(BigDecimal withdrawingMoney) {
        this.withdrawingMoney = withdrawingMoney;
    }

    public Integer getJoinType() {
        return joinType;
    }

    public void setJoinType(Integer joinType) {
        this.joinType = joinType;
    }

    public Integer getJoinStatus() {
        return joinStatus;
    }

    public void setJoinStatus(Integer joinStatus) {
        this.joinStatus = joinStatus;
    }

    public Boolean getDelete() {
        return isDelete;
    }

    public void setDelete(Boolean delete) {
        isDelete = delete;
    }

    public Integer getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(Integer updateDate) {
        this.updateDate = updateDate;
    }

    public Integer getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Integer createDate) {
        this.createDate = createDate;
    }

    public Integer getExtID() {
        return extID;
    }

    public void setExtID(Integer extID) {
        this.extID = extID;
    }

    public String getReceptionTel() {
        return receptionTel;
    }

    public void setReceptionTel(String receptionTel) {
        this.receptionTel = receptionTel;
    }

    public String getMobilePhone() {
        return mobilePhone;
    }

    public void setMobilePhone(String mobilePhone) {
        this.mobilePhone = mobilePhone;
    }

    public String getContactName() {
        return contactName;
    }

    public void setContactName(String contactName) {
        this.contactName = contactName;
    }

    public BigDecimal getMaxCreditMoney() {
        return maxCreditMoney;
    }

    public void setMaxCreditMoney(BigDecimal maxCreditMoney) {
        this.maxCreditMoney = maxCreditMoney;
    }

    public Integer getTerminateDate() {
        return terminateDate;
    }

    public void setTerminateDate(Integer terminateDate) {
        this.terminateDate = terminateDate;
    }

    public Integer getPullOffDate() {
        return pullOffDate;
    }

    public void setPullOffDate(Integer pullOffDate) {
        this.pullOffDate = pullOffDate;
    }
}