package com.zhiliao.hotel.model;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * @program: zhiliao_hotel_applets_api
 * @description
 * @author: 姬慧慧
 * @create: 2020-05-23 17:11
 **/
public class ZlHotelDetail implements Serializable {

    /**
     * 酒店详情ID
     */
    private Integer hoteldetailid;

    /**
     * 酒店ID
     */
    private Integer hotelid;

    /**
     * 房间数
     */
    private Integer roomcount;

    /**
     * 省编号(对应area表AreaID)
     */
    private Short provincecode;

    /**
     * 市编号(对应area表)
     */
    private Short citycode;

    /**
     * 区编号(对应area表)
     */
    private Short districtcode;

    /**
     * 酒店详细地址
     */
    private String address;

    /**
     * 经度
     */
    private Float longitude;

    /**
     * 纬度
     */
    private Float latitude;

    /**
     * 结算方式 百分比
     */
    private BigDecimal settlement;

    /**
     * 起送金额
     */
    private BigDecimal minsendcash;

    /**
     * 配送金额
     */
    private BigDecimal sendcash;

    /**
     * 合约图片,存储多个
     */
    private String contractimgurls;

    /**
     * 开户行
     */
    private String bank;

    /**
     * 开户行账号
     */
    private String bankaccountnumber;

    /**
     * 户名
     */
    private String bankaccountname;

    /**
     * 营业执照
     */
    private String bizlicenseurl;

    /**
     * 天气设置
     */
    private String weather;

    /**
     * 结算周期:1月结；2半月结；3周结;4季度结
     */
    private Byte billingcycle;

    /**
     * 保护期天数:0无保护期;在有效期内，平台不参与该酒店的销售分成
     */
    private Integer protectdays;

    /**
     * 酒店发票二维码
     */
    private String invoiceqrcodeurl;

    /**
     * 酒店前台二维码
     */
    private String receptionqrcodeurl;

    /**
     * 删除状态:0正常;1删除;
     */
    private Boolean isdelete;

    /**
     * 更新日期
     */
    private Integer updatedate;

    /**
     * 添加日期
     */
    private Integer createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zl_hoteldetail
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hoteldetail.HotelDetailID
     *
     * @return the value of zl_hoteldetail.HotelDetailID
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public Integer getHoteldetailid() {
        return hoteldetailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hoteldetail.HotelDetailID
     *
     * @param hoteldetailid the value for zl_hoteldetail.HotelDetailID
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public void setHoteldetailid(Integer hoteldetailid) {
        this.hoteldetailid = hoteldetailid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hoteldetail.HotelID
     *
     * @return the value of zl_hoteldetail.HotelID
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public Integer getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hoteldetail.HotelID
     *
     * @param hotelid the value for zl_hoteldetail.HotelID
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hoteldetail.RoomCount
     *
     * @return the value of zl_hoteldetail.RoomCount
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public Integer getRoomcount() {
        return roomcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hoteldetail.RoomCount
     *
     * @param roomcount the value for zl_hoteldetail.RoomCount
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public void setRoomcount(Integer roomcount) {
        this.roomcount = roomcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hoteldetail.ProvinceCode
     *
     * @return the value of zl_hoteldetail.ProvinceCode
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public Short getProvincecode() {
        return provincecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hoteldetail.ProvinceCode
     *
     * @param provincecode the value for zl_hoteldetail.ProvinceCode
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public void setProvincecode(Short provincecode) {
        this.provincecode = provincecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hoteldetail.CityCode
     *
     * @return the value of zl_hoteldetail.CityCode
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public Short getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hoteldetail.CityCode
     *
     * @param citycode the value for zl_hoteldetail.CityCode
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public void setCitycode(Short citycode) {
        this.citycode = citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hoteldetail.DistrictCode
     *
     * @return the value of zl_hoteldetail.DistrictCode
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public Short getDistrictcode() {
        return districtcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hoteldetail.DistrictCode
     *
     * @param districtcode the value for zl_hoteldetail.DistrictCode
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public void setDistrictcode(Short districtcode) {
        this.districtcode = districtcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hoteldetail.Address
     *
     * @return the value of zl_hoteldetail.Address
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hoteldetail.Address
     *
     * @param address the value for zl_hoteldetail.Address
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hoteldetail.Longitude
     *
     * @return the value of zl_hoteldetail.Longitude
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public Float getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hoteldetail.Longitude
     *
     * @param longitude the value for zl_hoteldetail.Longitude
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public void setLongitude(Float longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hoteldetail.Latitude
     *
     * @return the value of zl_hoteldetail.Latitude
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public Float getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hoteldetail.Latitude
     *
     * @param latitude the value for zl_hoteldetail.Latitude
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public void setLatitude(Float latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hoteldetail.Settlement
     *
     * @return the value of zl_hoteldetail.Settlement
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public BigDecimal getSettlement() {
        return settlement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hoteldetail.Settlement
     *
     * @param settlement the value for zl_hoteldetail.Settlement
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public void setSettlement(BigDecimal settlement) {
        this.settlement = settlement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hoteldetail.MinSendCash
     *
     * @return the value of zl_hoteldetail.MinSendCash
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public BigDecimal getMinsendcash() {
        return minsendcash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hoteldetail.MinSendCash
     *
     * @param minsendcash the value for zl_hoteldetail.MinSendCash
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public void setMinsendcash(BigDecimal minsendcash) {
        this.minsendcash = minsendcash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hoteldetail.SendCash
     *
     * @return the value of zl_hoteldetail.SendCash
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public BigDecimal getSendcash() {
        return sendcash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hoteldetail.SendCash
     *
     * @param sendcash the value for zl_hoteldetail.SendCash
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public void setSendcash(BigDecimal sendcash) {
        this.sendcash = sendcash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hoteldetail.ContractImgUrls
     *
     * @return the value of zl_hoteldetail.ContractImgUrls
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public String getContractimgurls() {
        return contractimgurls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hoteldetail.ContractImgUrls
     *
     * @param contractimgurls the value for zl_hoteldetail.ContractImgUrls
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public void setContractimgurls(String contractimgurls) {
        this.contractimgurls = contractimgurls == null ? null : contractimgurls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hoteldetail.Bank
     *
     * @return the value of zl_hoteldetail.Bank
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hoteldetail.Bank
     *
     * @param bank the value for zl_hoteldetail.Bank
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hoteldetail.BankAccountNumber
     *
     * @return the value of zl_hoteldetail.BankAccountNumber
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public String getBankaccountnumber() {
        return bankaccountnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hoteldetail.BankAccountNumber
     *
     * @param bankaccountnumber the value for zl_hoteldetail.BankAccountNumber
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public void setBankaccountnumber(String bankaccountnumber) {
        this.bankaccountnumber = bankaccountnumber == null ? null : bankaccountnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hoteldetail.BankAccountName
     *
     * @return the value of zl_hoteldetail.BankAccountName
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public String getBankaccountname() {
        return bankaccountname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hoteldetail.BankAccountName
     *
     * @param bankaccountname the value for zl_hoteldetail.BankAccountName
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public void setBankaccountname(String bankaccountname) {
        this.bankaccountname = bankaccountname == null ? null : bankaccountname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hoteldetail.BizLicenseUrl
     *
     * @return the value of zl_hoteldetail.BizLicenseUrl
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public String getBizlicenseurl() {
        return bizlicenseurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hoteldetail.BizLicenseUrl
     *
     * @param bizlicenseurl the value for zl_hoteldetail.BizLicenseUrl
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public void setBizlicenseurl(String bizlicenseurl) {
        this.bizlicenseurl = bizlicenseurl == null ? null : bizlicenseurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hoteldetail.Weather
     *
     * @return the value of zl_hoteldetail.Weather
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public String getWeather() {
        return weather;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hoteldetail.Weather
     *
     * @param weather the value for zl_hoteldetail.Weather
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public void setWeather(String weather) {
        this.weather = weather == null ? null : weather.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hoteldetail.BillingCycle
     *
     * @return the value of zl_hoteldetail.BillingCycle
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public Byte getBillingcycle() {
        return billingcycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hoteldetail.BillingCycle
     *
     * @param billingcycle the value for zl_hoteldetail.BillingCycle
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public void setBillingcycle(Byte billingcycle) {
        this.billingcycle = billingcycle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hoteldetail.ProtectDays
     *
     * @return the value of zl_hoteldetail.ProtectDays
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public Integer getProtectdays() {
        return protectdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hoteldetail.ProtectDays
     *
     * @param protectdays the value for zl_hoteldetail.ProtectDays
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public void setProtectdays(Integer protectdays) {
        this.protectdays = protectdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hoteldetail.InvoiceQrCodeUrl
     *
     * @return the value of zl_hoteldetail.InvoiceQrCodeUrl
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public String getInvoiceqrcodeurl() {
        return invoiceqrcodeurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hoteldetail.InvoiceQrCodeUrl
     *
     * @param invoiceqrcodeurl the value for zl_hoteldetail.InvoiceQrCodeUrl
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public void setInvoiceqrcodeurl(String invoiceqrcodeurl) {
        this.invoiceqrcodeurl = invoiceqrcodeurl == null ? null : invoiceqrcodeurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hoteldetail.ReceptionQrCodeUrl
     *
     * @return the value of zl_hoteldetail.ReceptionQrCodeUrl
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public String getReceptionqrcodeurl() {
        return receptionqrcodeurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hoteldetail.ReceptionQrCodeUrl
     *
     * @param receptionqrcodeurl the value for zl_hoteldetail.ReceptionQrCodeUrl
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public void setReceptionqrcodeurl(String receptionqrcodeurl) {
        this.receptionqrcodeurl = receptionqrcodeurl == null ? null : receptionqrcodeurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hoteldetail.IsDelete
     *
     * @return the value of zl_hoteldetail.IsDelete
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hoteldetail.IsDelete
     *
     * @param isdelete the value for zl_hoteldetail.IsDelete
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hoteldetail.UpdateDate
     *
     * @return the value of zl_hoteldetail.UpdateDate
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public Integer getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hoteldetail.UpdateDate
     *
     * @param updatedate the value for zl_hoteldetail.UpdateDate
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public void setUpdatedate(Integer updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hoteldetail.CreateDate
     *
     * @return the value of zl_hoteldetail.CreateDate
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public Integer getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hoteldetail.CreateDate
     *
     * @param createdate the value for zl_hoteldetail.CreateDate
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    public void setCreatedate(Integer createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zl_hoteldetail
     *
     * @mbg.generated Sat May 23 17:08:24 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", hoteldetailid=").append(hoteldetailid);
        sb.append(", hotelid=").append(hotelid);
        sb.append(", roomcount=").append(roomcount);
        sb.append(", provincecode=").append(provincecode);
        sb.append(", citycode=").append(citycode);
        sb.append(", districtcode=").append(districtcode);
        sb.append(", address=").append(address);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append(", settlement=").append(settlement);
        sb.append(", minsendcash=").append(minsendcash);
        sb.append(", sendcash=").append(sendcash);
        sb.append(", contractimgurls=").append(contractimgurls);
        sb.append(", bank=").append(bank);
        sb.append(", bankaccountnumber=").append(bankaccountnumber);
        sb.append(", bankaccountname=").append(bankaccountname);
        sb.append(", bizlicenseurl=").append(bizlicenseurl);
        sb.append(", weather=").append(weather);
        sb.append(", billingcycle=").append(billingcycle);
        sb.append(", protectdays=").append(protectdays);
        sb.append(", invoiceqrcodeurl=").append(invoiceqrcodeurl);
        sb.append(", receptionqrcodeurl=").append(receptionqrcodeurl);
        sb.append(", isdelete=").append(isdelete);
        sb.append(", updatedate=").append(updatedate);
        sb.append(", createdate=").append(createdate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

}
