package com.zhiliao.hotel.model;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * 
 *
 * @author null
 * @date 2020-04-29
 */
public class ZlHotelFacility implements Serializable {
    /**
     * 设施ID
     */
    private Integer facilityid;

    /**
     * 酒店ID
     */
    private Integer hotelid;

    /**
     * 剩余数量
     */
    private Integer facilitycount;

    /**
     * 设施名称
     */
    private String facilitynme;

    /**
     * 设施图片
     */
    private String imgurl;

    /**
     * 开放时间
     */
    private String serviceopentime;

    /**
     * 价格
     */
    private BigDecimal price;

    /**
     * 删除状态:0正常;1删除;
     */
    private Boolean isdelete;

    /**
     * 
     */
    private Integer createdate;

    /**
     * 
     */
    private Integer updatedate;

    /**
     * 详情
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zl_hotelfacility
     *
     * @mbg.generated Wed Apr 29 14:12:28 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelfacility.FacilityID
     *
     * @return the value of zl_hotelfacility.FacilityID
     *
     * @mbg.generated Wed Apr 29 14:12:28 CST 2020
     */
    public Integer getFacilityid() {
        return facilityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelfacility.FacilityID
     *
     * @param facilityid the value for zl_hotelfacility.FacilityID
     *
     * @mbg.generated Wed Apr 29 14:12:28 CST 2020
     */
    public void setFacilityid(Integer facilityid) {
        this.facilityid = facilityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelfacility.HotelID
     *
     * @return the value of zl_hotelfacility.HotelID
     *
     * @mbg.generated Wed Apr 29 14:12:28 CST 2020
     */
    public Integer getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelfacility.HotelID
     *
     * @param hotelid the value for zl_hotelfacility.HotelID
     *
     * @mbg.generated Wed Apr 29 14:12:28 CST 2020
     */
    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelfacility.FacilityCount
     *
     * @return the value of zl_hotelfacility.FacilityCount
     *
     * @mbg.generated Wed Apr 29 14:12:28 CST 2020
     */
    public Integer getFacilitycount() {
        return facilitycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelfacility.FacilityCount
     *
     * @param facilitycount the value for zl_hotelfacility.FacilityCount
     *
     * @mbg.generated Wed Apr 29 14:12:28 CST 2020
     */
    public void setFacilitycount(Integer facilitycount) {
        this.facilitycount = facilitycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelfacility.FacilityNme
     *
     * @return the value of zl_hotelfacility.FacilityNme
     *
     * @mbg.generated Wed Apr 29 14:12:28 CST 2020
     */
    public String getFacilitynme() {
        return facilitynme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelfacility.FacilityNme
     *
     * @param facilitynme the value for zl_hotelfacility.FacilityNme
     *
     * @mbg.generated Wed Apr 29 14:12:28 CST 2020
     */
    public void setFacilitynme(String facilitynme) {
        this.facilitynme = facilitynme == null ? null : facilitynme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelfacility.ImgUrl
     *
     * @return the value of zl_hotelfacility.ImgUrl
     *
     * @mbg.generated Wed Apr 29 14:12:28 CST 2020
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelfacility.ImgUrl
     *
     * @param imgurl the value for zl_hotelfacility.ImgUrl
     *
     * @mbg.generated Wed Apr 29 14:12:28 CST 2020
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelfacility.ServiceOpenTime
     *
     * @return the value of zl_hotelfacility.ServiceOpenTime
     *
     * @mbg.generated Wed Apr 29 14:12:28 CST 2020
     */
    public String getServiceopentime() {
        return serviceopentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelfacility.ServiceOpenTime
     *
     * @param serviceopentime the value for zl_hotelfacility.ServiceOpenTime
     *
     * @mbg.generated Wed Apr 29 14:12:28 CST 2020
     */
    public void setServiceopentime(String serviceopentime) {
        this.serviceopentime = serviceopentime == null ? null : serviceopentime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelfacility.Price
     *
     * @return the value of zl_hotelfacility.Price
     *
     * @mbg.generated Wed Apr 29 14:12:28 CST 2020
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelfacility.Price
     *
     * @param price the value for zl_hotelfacility.Price
     *
     * @mbg.generated Wed Apr 29 14:12:28 CST 2020
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelfacility.IsDelete
     *
     * @return the value of zl_hotelfacility.IsDelete
     *
     * @mbg.generated Wed Apr 29 14:12:28 CST 2020
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelfacility.IsDelete
     *
     * @param isdelete the value for zl_hotelfacility.IsDelete
     *
     * @mbg.generated Wed Apr 29 14:12:28 CST 2020
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelfacility.CreateDate
     *
     * @return the value of zl_hotelfacility.CreateDate
     *
     * @mbg.generated Wed Apr 29 14:12:28 CST 2020
     */
    public Integer getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelfacility.CreateDate
     *
     * @param createdate the value for zl_hotelfacility.CreateDate
     *
     * @mbg.generated Wed Apr 29 14:12:28 CST 2020
     */
    public void setCreatedate(Integer createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelfacility.UpdateDate
     *
     * @return the value of zl_hotelfacility.UpdateDate
     *
     * @mbg.generated Wed Apr 29 14:12:28 CST 2020
     */
    public Integer getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelfacility.UpdateDate
     *
     * @param updatedate the value for zl_hotelfacility.UpdateDate
     *
     * @mbg.generated Wed Apr 29 14:12:28 CST 2020
     */
    public void setUpdatedate(Integer updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelfacility.Content
     *
     * @return the value of zl_hotelfacility.Content
     *
     * @mbg.generated Wed Apr 29 14:12:28 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelfacility.Content
     *
     * @param content the value for zl_hotelfacility.Content
     *
     * @mbg.generated Wed Apr 29 14:12:28 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zl_hotelfacility
     *
     * @mbg.generated Wed Apr 29 14:12:28 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", facilityid=").append(facilityid);
        sb.append(", hotelid=").append(hotelid);
        sb.append(", facilitycount=").append(facilitycount);
        sb.append(", facilitynme=").append(facilitynme);
        sb.append(", imgurl=").append(imgurl);
        sb.append(", serviceopentime=").append(serviceopentime);
        sb.append(", price=").append(price);
        sb.append(", isdelete=").append(isdelete);
        sb.append(", createdate=").append(createdate);
        sb.append(", updatedate=").append(updatedate);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}