package com.zhiliao.hotel.model;

import java.io.Serializable;

/**
 * 
 *
 * @author null
 * @date 2020-05-21
 */
public class ZlHotelGoods implements Serializable {
    /**
     * 自增ID
     */
    private Integer hotelgoodsid;

    /**
     * 酒店ID
     */
    private Integer hotelid;

    /**
     * 供应商ID
     */
    private Integer supplierid;

    /**
     * 商品类别
     */
    private Integer goodscategoryid;

    /**
     * SkuID
     */
    private Integer skuid;

    /**
     * 商品ID
     */
    private Integer goodsid;

    /**
     * -1被紧急下架；0下架；1上架
     */
    private Byte goodsstatus;

    /**
     * 库存
     */
    private Integer stockcount;

    /**
     * 销量
     */
    private Integer soldcount;

    /**
     * 0正常；1删除
     */
    private Boolean isdelete;

    /**
     * 创建时间
     */
    private Integer createdate;

    /**
     * 修改时间
     */
    private Integer updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zl_hotelgoods
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelgoods.HotelGoodsID
     *
     * @return the value of zl_hotelgoods.HotelGoodsID
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    public Integer getHotelgoodsid() {
        return hotelgoodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelgoods.HotelGoodsID
     *
     * @param hotelgoodsid the value for zl_hotelgoods.HotelGoodsID
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    public void setHotelgoodsid(Integer hotelgoodsid) {
        this.hotelgoodsid = hotelgoodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelgoods.HotelID
     *
     * @return the value of zl_hotelgoods.HotelID
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    public Integer getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelgoods.HotelID
     *
     * @param hotelid the value for zl_hotelgoods.HotelID
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelgoods.SupplierID
     *
     * @return the value of zl_hotelgoods.SupplierID
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    public Integer getSupplierid() {
        return supplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelgoods.SupplierID
     *
     * @param supplierid the value for zl_hotelgoods.SupplierID
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    public void setSupplierid(Integer supplierid) {
        this.supplierid = supplierid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelgoods.GoodsCategoryID
     *
     * @return the value of zl_hotelgoods.GoodsCategoryID
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    public Integer getGoodscategoryid() {
        return goodscategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelgoods.GoodsCategoryID
     *
     * @param goodscategoryid the value for zl_hotelgoods.GoodsCategoryID
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    public void setGoodscategoryid(Integer goodscategoryid) {
        this.goodscategoryid = goodscategoryid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelgoods.SkuID
     *
     * @return the value of zl_hotelgoods.SkuID
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    public Integer getSkuid() {
        return skuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelgoods.SkuID
     *
     * @param skuid the value for zl_hotelgoods.SkuID
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    public void setSkuid(Integer skuid) {
        this.skuid = skuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelgoods.GoodsID
     *
     * @return the value of zl_hotelgoods.GoodsID
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelgoods.GoodsID
     *
     * @param goodsid the value for zl_hotelgoods.GoodsID
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelgoods.GoodsStatus
     *
     * @return the value of zl_hotelgoods.GoodsStatus
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    public Byte getGoodsstatus() {
        return goodsstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelgoods.GoodsStatus
     *
     * @param goodsstatus the value for zl_hotelgoods.GoodsStatus
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    public void setGoodsstatus(Byte goodsstatus) {
        this.goodsstatus = goodsstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelgoods.StockCount
     *
     * @return the value of zl_hotelgoods.StockCount
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    public Integer getStockcount() {
        return stockcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelgoods.StockCount
     *
     * @param stockcount the value for zl_hotelgoods.StockCount
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    public void setStockcount(Integer stockcount) {
        this.stockcount = stockcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelgoods.SoldCount
     *
     * @return the value of zl_hotelgoods.SoldCount
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    public Integer getSoldcount() {
        return soldcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelgoods.SoldCount
     *
     * @param soldcount the value for zl_hotelgoods.SoldCount
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    public void setSoldcount(Integer soldcount) {
        this.soldcount = soldcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelgoods.IsDelete
     *
     * @return the value of zl_hotelgoods.IsDelete
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelgoods.IsDelete
     *
     * @param isdelete the value for zl_hotelgoods.IsDelete
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelgoods.CreateDate
     *
     * @return the value of zl_hotelgoods.CreateDate
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    public Integer getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelgoods.CreateDate
     *
     * @param createdate the value for zl_hotelgoods.CreateDate
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    public void setCreatedate(Integer createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotelgoods.UpdateDate
     *
     * @return the value of zl_hotelgoods.UpdateDate
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    public Integer getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_hotelgoods.UpdateDate
     *
     * @param updatedate the value for zl_hotelgoods.UpdateDate
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    public void setUpdatedate(Integer updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zl_hotelgoods
     *
     * @mbg.generated Thu May 21 15:56:49 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", hotelgoodsid=").append(hotelgoodsid);
        sb.append(", hotelid=").append(hotelid);
        sb.append(", supplierid=").append(supplierid);
        sb.append(", goodscategoryid=").append(goodscategoryid);
        sb.append(", skuid=").append(skuid);
        sb.append(", goodsid=").append(goodsid);
        sb.append(", goodsstatus=").append(goodsstatus);
        sb.append(", stockcount=").append(stockcount);
        sb.append(", soldcount=").append(soldcount);
        sb.append(", isdelete=").append(isdelete);
        sb.append(", createdate=").append(createdate);
        sb.append(", updatedate=").append(updatedate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}