package com.zhiliao.hotel.model;

import java.io.Serializable;

/**
 * 
 *
 * @author null
 * @date 2020-04-14
 */
public class ZlInvoice implements Serializable {
    /**
     * 发票ID
     */
    private Integer invoiceid;

    /**
     * 用户ID
     */
    private Long userid;

    /**
     * 发票类型:1:增值税普通发票;2增值税专用发票
     */
    private Byte invoicetype;

    /**
     * 发票类型:(主体)1: 个人;2单位
     */
    private Byte mainbodytype;

    /**
     * 0电子发票；1纸质发票
     */
    private Byte electronicpapertype;

    /**
     * 个人真实姓/或单位抬头
     */
    private String title;

    /**
     * 
单位的纳税人识别号:15/18或20位
     */
    private String identifier;

    /**
     * 
个人或单位电话号码
     */
    private String tel;

    /**
     * 备注信息
     */
    private String remark;

    /**
     * 开票状态 -1:已取消;0:未开票;1开票中;2已开票
     */
    private Byte invoicestatus;

    /**
     * 开户行
     */
    private String bank;

    /**
     * 开户行账号
     */
    private String bankaccountnumber;

    /**
     * 单位电话
     */
    private String companytel;

    /**
     * 单位地址
     */
    private String companyaddress;

    /**
     * 删除状态:0正常;1删除;
     */
    private Boolean isdelete;

    /**
     * 添加时间
     */
    private Integer createdate;

    /**
     * 修改时间
     */
    private Integer updatedate;

    /**
     * 服务类型
     */
    private String fuwutype;

    public String getFuwutype() {
        return fuwutype;
    }

    public void setFuwutype(String fuwutype) {
        this.fuwutype = fuwutype;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zl_invoice
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_invoice.InvoiceID
     *
     * @return the value of zl_invoice.InvoiceID
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public Integer getInvoiceid() {
        return invoiceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_invoice.InvoiceID
     *
     * @param invoiceid the value for zl_invoice.InvoiceID
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public void setInvoiceid(Integer invoiceid) {
        this.invoiceid = invoiceid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_invoice.UserID
     *
     * @return the value of zl_invoice.UserID
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_invoice.UserID
     *
     * @param userid the value for zl_invoice.UserID
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_invoice.InvoiceType
     *
     * @return the value of zl_invoice.InvoiceType
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public Byte getInvoicetype() {
        return invoicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_invoice.InvoiceType
     *
     * @param invoicetype the value for zl_invoice.InvoiceType
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public void setInvoicetype(Byte invoicetype) {
        this.invoicetype = invoicetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_invoice.MainBodyType
     *
     * @return the value of zl_invoice.MainBodyType
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public Byte getMainbodytype() {
        return mainbodytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_invoice.MainBodyType
     *
     * @param mainbodytype the value for zl_invoice.MainBodyType
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public void setMainbodytype(Byte mainbodytype) {
        this.mainbodytype = mainbodytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_invoice.ElectronicPaperType
     *
     * @return the value of zl_invoice.ElectronicPaperType
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public Byte getElectronicpapertype() {
        return electronicpapertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_invoice.ElectronicPaperType
     *
     * @param electronicpapertype the value for zl_invoice.ElectronicPaperType
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public void setElectronicpapertype(Byte electronicpapertype) {
        this.electronicpapertype = electronicpapertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_invoice.Title
     *
     * @return the value of zl_invoice.Title
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_invoice.Title
     *
     * @param title the value for zl_invoice.Title
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_invoice.Identifier
     *
     * @return the value of zl_invoice.Identifier
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_invoice.Identifier
     *
     * @param identifier the value for zl_invoice.Identifier
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public void setIdentifier(String identifier) {
        this.identifier = identifier == null ? null : identifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_invoice.Tel
     *
     * @return the value of zl_invoice.Tel
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_invoice.Tel
     *
     * @param tel the value for zl_invoice.Tel
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_invoice.Remark
     *
     * @return the value of zl_invoice.Remark
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_invoice.Remark
     *
     * @param remark the value for zl_invoice.Remark
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_invoice.InvoiceStatus
     *
     * @return the value of zl_invoice.InvoiceStatus
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public Byte getInvoicestatus() {
        return invoicestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_invoice.InvoiceStatus
     *
     * @param invoicestatus the value for zl_invoice.InvoiceStatus
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public void setInvoicestatus(Byte invoicestatus) {
        this.invoicestatus = invoicestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_invoice.Bank
     *
     * @return the value of zl_invoice.Bank
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public String getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_invoice.Bank
     *
     * @param bank the value for zl_invoice.Bank
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public void setBank(String bank) {
        this.bank = bank == null ? null : bank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_invoice.BankAccountNumber
     *
     * @return the value of zl_invoice.BankAccountNumber
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public String getBankaccountnumber() {
        return bankaccountnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_invoice.BankAccountNumber
     *
     * @param bankaccountnumber the value for zl_invoice.BankAccountNumber
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public void setBankaccountnumber(String bankaccountnumber) {
        this.bankaccountnumber = bankaccountnumber == null ? null : bankaccountnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_invoice.CompanyTel
     *
     * @return the value of zl_invoice.CompanyTel
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public String getCompanytel() {
        return companytel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_invoice.CompanyTel
     *
     * @param companytel the value for zl_invoice.CompanyTel
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public void setCompanytel(String companytel) {
        this.companytel = companytel == null ? null : companytel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_invoice.CompanyAddress
     *
     * @return the value of zl_invoice.CompanyAddress
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public String getCompanyaddress() {
        return companyaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_invoice.CompanyAddress
     *
     * @param companyaddress the value for zl_invoice.CompanyAddress
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public void setCompanyaddress(String companyaddress) {
        this.companyaddress = companyaddress == null ? null : companyaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_invoice.IsDelete
     *
     * @return the value of zl_invoice.IsDelete
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_invoice.IsDelete
     *
     * @param isdelete the value for zl_invoice.IsDelete
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_invoice.CreateDate
     *
     * @return the value of zl_invoice.CreateDate
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public Integer getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_invoice.CreateDate
     *
     * @param createdate the value for zl_invoice.CreateDate
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public void setCreatedate(Integer createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_invoice.UpdateDate
     *
     * @return the value of zl_invoice.UpdateDate
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public Integer getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_invoice.UpdateDate
     *
     * @param updatedate the value for zl_invoice.UpdateDate
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    public void setUpdatedate(Integer updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zl_invoice
     *
     * @mbg.generated Tue Apr 14 16:21:17 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", invoiceid=").append(invoiceid);
        sb.append(", userid=").append(userid);
        sb.append(", invoicetype=").append(invoicetype);
        sb.append(", mainbodytype=").append(mainbodytype);
        sb.append(", electronicpapertype=").append(electronicpapertype);
        sb.append(", title=").append(title);
        sb.append(", identifier=").append(identifier);
        sb.append(", tel=").append(tel);
        sb.append(", remark=").append(remark);
        sb.append(", invoicestatus=").append(invoicestatus);
        sb.append(", bank=").append(bank);
        sb.append(", bankaccountnumber=").append(bankaccountnumber);
        sb.append(", companytel=").append(companytel);
        sb.append(", companyaddress=").append(companyaddress);
        sb.append(", isdelete=").append(isdelete);
        sb.append(", createdate=").append(createdate);
        sb.append(", updatedate=").append(updatedate);
        sb.append(", fuwutype=").append(fuwutype);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}