package com.zhiliao.hotel.model;

import javax.persistence.Id;
import java.io.Serializable;

public class ZlMenuvisitlog implements Serializable {
    /**
     * 记录ID
     */
    @Id
    private Long logid;

    /**
     * 模块ID(菜单ID)
     */
    private Integer menuid;

    /**
     * 用户IP
     */
    private String userip;

    /**
     * 用户ID
     */
    private Integer userid;

    /**
     * 创建时间（点击时间）
     */
    private Integer createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zl_menuvisitlog
     *
     * @mbg.generated Thu Apr 16 17:15:32 SGT 2020
     */
    private static final long serialVersionUID = 1L;

    public Long getLogid() {
        return logid;
    }

    public void setLogid(Long logid) {
        this.logid = logid;
    }

    public Integer getMenuid() {
        return menuid;
    }

    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    public String getUserip() {
        return userip;
    }

    public void setUserip(String userip) {
        this.userip = userip;
    }

    public Integer getUserid() {
        return userid;
    }

    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    public Integer getCreatedate() {
        return createdate;
    }

    public void setCreatedate(Integer createdate) {
        this.createdate = createdate;
    }
}
