package com.zhiliao.hotel.model;

import java.io.Serializable;

/**
 * 
 *
 * @author null
 * @date 2020-04-14
 */
public class ZlNews implements Serializable {
    /**
     * 主键
     */
    private Integer newsid;

    /**
     * 酒店id; id=0时为系统新闻或系统公告
     */
    private Integer hotelid;

    /**
     * 1:公告;2新闻资讯
     */
    private Byte type;

    /**
     * 作者
     */
    private String author;

    /**
     * 标题
     */
    private String title;

    /**
     * 简介
     */
    private String description;

    /**
     * 缩略图
     */
    private String imgurl;

    /**
     * 阅读数
     */
    private Integer visitcount;

    /**
     * 排序
     */
    private Short sort;

    /**
     * 是否启用 0:否;1:是
     */
    private Boolean status;

    public Integer getCheckstatus() {
        return checkstatus;
    }

    public void setCheckstatus(Integer checkstatus) {
        this.checkstatus = checkstatus;
    }

    /**
     * 审核状态:-1驳回;0待审核;1审核中;2审核通过
     */
    private Integer checkstatus;

    /**
     * 创建人
     */
    private String creatorusername;

    /**
     * 添加ip
     */
    private String creatorusrip;

    /**
     * 修改人
     */
    private String modifyusername;

    /**
     * 修改ip
     */
    private String modifyuserip;

    /**
     * 新闻时间
     */
    private Integer createdate;

    /**
     * 修改时间
     */
    private Integer updatedate;

    /**
     * 内容
     */
    private String content;

    /**
     * 酒店名称
     */
    private String hotelName;

    public Integer getIsDelete() {
        return isDelete;
    }

    public void setIsDelete(Integer isDelete) {
        this.isDelete = isDelete;
    }

    private Integer isDelete;

    public String getHotelName() {
        return hotelName;
    }

    public void setHotelName(String hotelName) {
        this.hotelName = hotelName;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zl_news
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_news.NewsID
     *
     * @return the value of zl_news.NewsID
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public Integer getNewsid() {
        return newsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_news.NewsID
     *
     * @param newsid the value for zl_news.NewsID
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public void setNewsid(Integer newsid) {
        this.newsid = newsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_news.HotelID
     *
     * @return the value of zl_news.HotelID
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public Integer getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_news.HotelID
     *
     * @param hotelid the value for zl_news.HotelID
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_news.Type
     *
     * @return the value of zl_news.Type
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_news.Type
     *
     * @param type the value for zl_news.Type
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_news.Author
     *
     * @return the value of zl_news.Author
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_news.Author
     *
     * @param author the value for zl_news.Author
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_news.Title
     *
     * @return the value of zl_news.Title
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_news.Title
     *
     * @param title the value for zl_news.Title
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_news.Description
     *
     * @return the value of zl_news.Description
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_news.Description
     *
     * @param description the value for zl_news.Description
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_news.ImgUrl
     *
     * @return the value of zl_news.ImgUrl
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public String getImgurl() {
        return imgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_news.ImgUrl
     *
     * @param imgurl the value for zl_news.ImgUrl
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public void setImgurl(String imgurl) {
        this.imgurl = imgurl == null ? null : imgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_news.VisitCount
     *
     * @return the value of zl_news.VisitCount
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public Integer getVisitcount() {
        return visitcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_news.VisitCount
     *
     * @param visitcount the value for zl_news.VisitCount
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public void setVisitcount(Integer visitcount) {
        this.visitcount = visitcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_news.Sort
     *
     * @return the value of zl_news.Sort
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public Short getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_news.Sort
     *
     * @param sort the value for zl_news.Sort
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public void setSort(Short sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_news.Status
     *
     * @return the value of zl_news.Status
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_news.Status
     *
     * @param status the value for zl_news.Status
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_news.CreatorUserName
     *
     * @return the value of zl_news.CreatorUserName
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public String getCreatorusername() {
        return creatorusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_news.CreatorUserName
     *
     * @param creatorusername the value for zl_news.CreatorUserName
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public void setCreatorusername(String creatorusername) {
        this.creatorusername = creatorusername == null ? null : creatorusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_news.CreatorUsrIP
     *
     * @return the value of zl_news.CreatorUsrIP
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public String getCreatorusrip() {
        return creatorusrip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_news.CreatorUsrIP
     *
     * @param creatorusrip the value for zl_news.CreatorUsrIP
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public void setCreatorusrip(String creatorusrip) {
        this.creatorusrip = creatorusrip == null ? null : creatorusrip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_news.ModifyUserName
     *
     * @return the value of zl_news.ModifyUserName
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public String getModifyusername() {
        return modifyusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_news.ModifyUserName
     *
     * @param modifyusername the value for zl_news.ModifyUserName
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public void setModifyusername(String modifyusername) {
        this.modifyusername = modifyusername == null ? null : modifyusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_news.ModifyUserIP
     *
     * @return the value of zl_news.ModifyUserIP
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public String getModifyuserip() {
        return modifyuserip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_news.ModifyUserIP
     *
     * @param modifyuserip the value for zl_news.ModifyUserIP
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public void setModifyuserip(String modifyuserip) {
        this.modifyuserip = modifyuserip == null ? null : modifyuserip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_news.CreateDate
     *
     * @return the value of zl_news.CreateDate
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public Integer getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_news.CreateDate
     *
     * @param createdate the value for zl_news.CreateDate
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public void setCreatedate(Integer createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_news.UpdateDate
     *
     * @return the value of zl_news.UpdateDate
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public Integer getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_news.UpdateDate
     *
     * @param updatedate the value for zl_news.UpdateDate
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public void setUpdatedate(Integer updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_news.Content
     *
     * @return the value of zl_news.Content
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_news.Content
     *
     * @param content the value for zl_news.Content
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zl_news
     *
     * @mbg.generated Tue Apr 14 10:45:02 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", newsid=").append(newsid);
        sb.append(", hotelid=").append(hotelid);
        sb.append(", type=").append(type);
        sb.append(", author=").append(author);
        sb.append(", title=").append(title);
        sb.append(", description=").append(description);
        sb.append(", imgurl=").append(imgurl);
        sb.append(", visitcount=").append(visitcount);
        sb.append(", sort=").append(sort);
        sb.append(", status=").append(status);
        sb.append(", creatorusername=").append(creatorusername);
        sb.append(", creatorusrip=").append(creatorusrip);
        sb.append(", modifyusername=").append(modifyusername);
        sb.append(", modifyuserip=").append(modifyuserip);
        sb.append(", createdate=").append(createdate);
        sb.append(", updatedate=").append(updatedate);
        sb.append(", content=").append(content);
        sb.append(", hotelName=").append(hotelName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}