package com.zhiliao.hotel.model;

import java.io.Serializable;

/**
 * 报修信息实体类
 *
 * @author null
 * @date 2020-04-14
 */
public class ZlRepair implements Serializable {
    /**
     * 维修ID
     */
    private Long repairid;

    /**
     * 用户ID
     */
    private Long userid;

    /**
     * 酒店ID
     */
    private Integer hotelid;

    /**
     * 房间ID
     */
    private Integer roomid;

    /**
     * 房间号
     */
    private String roomnumber;

    /**
     * 报修信息
     */
    private String remark;

    /**
     * 一个或多个图片地址;
     */
    private String imgurls;

    /**
     * 维状态:0未维修;1维修中;2已维修;
     */
    private Byte repairstatus;

    /**
     * 删除状态:0正常;1删除;
     */
    private Boolean isdelete;

    /**
     * 预约时间
     */
    private Integer appointmentdate;

    /**
     * 添加日期
     */
    private Integer createdate;

    /**
     * 更新日期
     */
    private Integer updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zl_repair
     *
     * @mbg.generated Tue Apr 14 10:17:21 CST 2020
     */
    private static final long serialVersionUID = 1L;


    @Override
    public String toString() {
        return "ZlRepair{" +
                "repairid=" + repairid +
                ", userid=" + userid +
                ", hotelid=" + hotelid +
                ", roomid=" + roomid +
                ", roomnumber='" + roomnumber + '\'' +
                ", remark='" + remark + '\'' +
                ", imgurls='" + imgurls + '\'' +
                ", repairstatus=" + repairstatus +
                ", isdelete=" + isdelete +
                ", appointmentdate=" + appointmentdate +
                ", createdate=" + createdate +
                ", updatedate=" + updatedate +
                '}';
    }

    public Long getRepairid() {
        return repairid;
    }

    public void setRepairid(Long repairid) {
        this.repairid = repairid;
    }

    public Long getUserid() {
        return userid;
    }

    public void setUserid(Long userid) {
        this.userid = userid;
    }

    public Integer getHotelid() {
        return hotelid;
    }

    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    public Integer getRoomid() {
        return roomid;
    }

    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }

    public String getRoomnumber() {
        return roomnumber;
    }

    public void setRoomnumber(String roomnumber) {
        this.roomnumber = roomnumber;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getImgurls() {
        return imgurls;
    }

    public void setImgurls(String imgurls) {
        this.imgurls = imgurls;
    }

    public Byte getRepairstatus() {
        return repairstatus;
    }

    public void setRepairstatus(Byte repairstatus) {
        this.repairstatus = repairstatus;
    }

    public Boolean getIsdelete() {
        return isdelete;
    }

    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    public Integer getAppointmentdate() {
        return appointmentdate;
    }

    public void setAppointmentdate(Integer appointmentdate) {
        this.appointmentdate = appointmentdate;
    }

    public Integer getCreatedate() {
        return createdate;
    }

    public void setCreatedate(Integer createdate) {
        this.createdate = createdate;
    }

    public Integer getUpdatedate() {
        return updatedate;
    }

    public void setUpdatedate(Integer updatedate) {
        this.updatedate = updatedate;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }
}