package com.zhiliao.hotel.model;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * 
 *
 * @author null
 * @date 2020-06-06
 */
public class ZlRentCarGoods implements Serializable {
    /**
     * 商品ID
     */
    private Integer goodsid;

    /**
     * 酒店ID
     */
    private Integer hotelid;

    /**
     * 商品图片
     */
    private String coverimgurl;

    /**
     * 租车车型号
     */
    private String goodsname;

    /**
     * 车牌号
     */
    private String carnumber;

    /**
     * 品牌等标签“|”隔开
     */
    private String tags;

    /**
     * 租金/时
     */
    private BigDecimal rentprice;

    /**
     * 库存
     */
    private Integer stockcount;

    /**
     * 
     */
    private Integer realtimestockcount;

    /**
     * 可取消订单时间(分钟)
     */
    private Integer cancancelorderminute;

    /**
     * 0:下架;1上架
     */
    private Byte goodsstatus;

    /**
     * 审核状态:-1拒绝;0待提交;1待审核;2审核通过
     */
    private Byte checkstatus;

    /**
     * 排序
     */
    private Integer sort;

    /**
     * 删除状态:0正常;1删除;
     */
    private Boolean isdelete;

    /**
     * 添加时间
     */
    private Integer createdate;

    /**
     * 修改时间
     */
    private Integer updatedate;

    /**
     * 租车详情
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zl_rentcargoods
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcargoods.GoodsID
     *
     * @return the value of zl_rentcargoods.GoodsID
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public Integer getGoodsid() {
        return goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcargoods.GoodsID
     *
     * @param goodsid the value for zl_rentcargoods.GoodsID
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public void setGoodsid(Integer goodsid) {
        this.goodsid = goodsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcargoods.HotelID
     *
     * @return the value of zl_rentcargoods.HotelID
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public Integer getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcargoods.HotelID
     *
     * @param hotelid the value for zl_rentcargoods.HotelID
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcargoods.CoverImgUrl
     *
     * @return the value of zl_rentcargoods.CoverImgUrl
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public String getCoverimgurl() {
        return coverimgurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcargoods.CoverImgUrl
     *
     * @param coverimgurl the value for zl_rentcargoods.CoverImgUrl
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public void setCoverimgurl(String coverimgurl) {
        this.coverimgurl = coverimgurl == null ? null : coverimgurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcargoods.GoodsName
     *
     * @return the value of zl_rentcargoods.GoodsName
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcargoods.GoodsName
     *
     * @param goodsname the value for zl_rentcargoods.GoodsName
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname == null ? null : goodsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcargoods.CarNumber
     *
     * @return the value of zl_rentcargoods.CarNumber
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public String getCarnumber() {
        return carnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcargoods.CarNumber
     *
     * @param carnumber the value for zl_rentcargoods.CarNumber
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public void setCarnumber(String carnumber) {
        this.carnumber = carnumber == null ? null : carnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcargoods.Tags
     *
     * @return the value of zl_rentcargoods.Tags
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public String getTags() {
        return tags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcargoods.Tags
     *
     * @param tags the value for zl_rentcargoods.Tags
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public void setTags(String tags) {
        this.tags = tags == null ? null : tags.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcargoods.RentPrice
     *
     * @return the value of zl_rentcargoods.RentPrice
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public BigDecimal getRentprice() {
        return rentprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcargoods.RentPrice
     *
     * @param rentprice the value for zl_rentcargoods.RentPrice
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public void setRentprice(BigDecimal rentprice) {
        this.rentprice = rentprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcargoods.StockCount
     *
     * @return the value of zl_rentcargoods.StockCount
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public Integer getStockcount() {
        return stockcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcargoods.StockCount
     *
     * @param stockcount the value for zl_rentcargoods.StockCount
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public void setStockcount(Integer stockcount) {
        this.stockcount = stockcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcargoods.RealtimeStockCount
     *
     * @return the value of zl_rentcargoods.RealtimeStockCount
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public Integer getRealtimestockcount() {
        return realtimestockcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcargoods.RealtimeStockCount
     *
     * @param realtimestockcount the value for zl_rentcargoods.RealtimeStockCount
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public void setRealtimestockcount(Integer realtimestockcount) {
        this.realtimestockcount = realtimestockcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcargoods.CanCancelOrderMinute
     *
     * @return the value of zl_rentcargoods.CanCancelOrderMinute
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public Integer getCancancelorderminute() {
        return cancancelorderminute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcargoods.CanCancelOrderMinute
     *
     * @param cancancelorderminute the value for zl_rentcargoods.CanCancelOrderMinute
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public void setCancancelorderminute(Integer cancancelorderminute) {
        this.cancancelorderminute = cancancelorderminute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcargoods.GoodsStatus
     *
     * @return the value of zl_rentcargoods.GoodsStatus
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public Byte getGoodsstatus() {
        return goodsstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcargoods.GoodsStatus
     *
     * @param goodsstatus the value for zl_rentcargoods.GoodsStatus
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public void setGoodsstatus(Byte goodsstatus) {
        this.goodsstatus = goodsstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcargoods.CheckStatus
     *
     * @return the value of zl_rentcargoods.CheckStatus
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public Byte getCheckstatus() {
        return checkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcargoods.CheckStatus
     *
     * @param checkstatus the value for zl_rentcargoods.CheckStatus
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public void setCheckstatus(Byte checkstatus) {
        this.checkstatus = checkstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcargoods.Sort
     *
     * @return the value of zl_rentcargoods.Sort
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcargoods.Sort
     *
     * @param sort the value for zl_rentcargoods.Sort
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcargoods.IsDelete
     *
     * @return the value of zl_rentcargoods.IsDelete
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcargoods.IsDelete
     *
     * @param isdelete the value for zl_rentcargoods.IsDelete
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcargoods.CreateDate
     *
     * @return the value of zl_rentcargoods.CreateDate
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public Integer getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcargoods.CreateDate
     *
     * @param createdate the value for zl_rentcargoods.CreateDate
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public void setCreatedate(Integer createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcargoods.UpdateDate
     *
     * @return the value of zl_rentcargoods.UpdateDate
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public Integer getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcargoods.UpdateDate
     *
     * @param updatedate the value for zl_rentcargoods.UpdateDate
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public void setUpdatedate(Integer updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcargoods.Content
     *
     * @return the value of zl_rentcargoods.Content
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcargoods.Content
     *
     * @param content the value for zl_rentcargoods.Content
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zl_rentcargoods
     *
     * @mbg.generated Sat Jun 06 08:53:52 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", goodsid=").append(goodsid);
        sb.append(", hotelid=").append(hotelid);
        sb.append(", coverimgurl=").append(coverimgurl);
        sb.append(", goodsname=").append(goodsname);
        sb.append(", carnumber=").append(carnumber);
        sb.append(", tags=").append(tags);
        sb.append(", rentprice=").append(rentprice);
        sb.append(", stockcount=").append(stockcount);
        sb.append(", realtimestockcount=").append(realtimestockcount);
        sb.append(", cancancelorderminute=").append(cancancelorderminute);
        sb.append(", goodsstatus=").append(goodsstatus);
        sb.append(", checkstatus=").append(checkstatus);
        sb.append(", sort=").append(sort);
        sb.append(", isdelete=").append(isdelete);
        sb.append(", createdate=").append(createdate);
        sb.append(", updatedate=").append(updatedate);
        sb.append(", content=").append(content);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}