package com.zhiliao.hotel.model;

import org.springframework.data.annotation.Id;

import javax.persistence.GeneratedValue;
import javax.persistence.Table;
import java.io.Serializable;
import java.math.BigDecimal;

/**
 * 
 *
 * @author null
 * @date 2020-06-06
 */
@Table(name = "zl_rentcarorder")
public class ZlRentCarOrder implements Serializable {
    /**
     * 订单ID
     */
    @Id
    @GeneratedValue(generator = "JDBC")
    private Long orderid;

    /**
     * 用户ID
     */
    private Long userid;

    /**
     * 订单编号
     */
    private String orderserialno;

    /**
     * 酒店ID
     */
    private Integer hotelid;

    /**
     * 酒店名
     */
    private String hotelname;

    /**
     * 房间ID
     */
    private Integer roomid;

    /**
     * 房间号
     */
    private String roomnumber;

    /**
     * 用户名
     */
    private String username;

    /**
     * 手机
     */
    private String tel;

    /**
     * 订单状态:-1:已取消;0待处理;1处理完成
     */
    private Byte orderstatus;

    /**
     * 操作员
     */
    private String operatorname;

    /**
     * 操作员IP
     */
    private String operatorip;

    /**
     * 操作员备注
     */
    private String operatorremark;

    /**
     * 租车车型号
     */
    private String goodsname;

    /**
     * 车牌号
     */
    private String carnumber;

    /**
     * 租车开始时间
     */
    private Integer rentbegindate;

    /**
     * 租车结束时间
     */
    private Integer rentenddate;

    /**
     * 归还时间
     */
    private Integer givebackdate;

    /**
     * 租金/天
     */
    private BigDecimal rentprice;

    /**
     * 租车费用
     */
    private BigDecimal renttotalprice;

    /**
     * 可取消订单时间(分钟)
     */
    private Integer cancancelorderminute;

    /**
     * 备注
     */
    private String remark;

    /**
     * 删除状态:0正常;1删除;
     */
    private Boolean isdelete;

    /**
     * 用户删除:0否;1是
     */
    private Boolean isuserdelete;

    /**
     * 创建时间（下单时间)
     */
    private Integer createdate;

    /**
     * 修改时间（操作时间）
     */
    private Integer updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zl_rentcarorder
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.OrderID
     *
     * @return the value of zl_rentcarorder.OrderID
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.OrderID
     *
     * @param orderid the value for zl_rentcarorder.OrderID
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.UserID
     *
     * @return the value of zl_rentcarorder.UserID
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.UserID
     *
     * @param userid the value for zl_rentcarorder.UserID
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.OrderSerialNo
     *
     * @return the value of zl_rentcarorder.OrderSerialNo
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public String getOrderserialno() {
        return orderserialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.OrderSerialNo
     *
     * @param orderserialno the value for zl_rentcarorder.OrderSerialNo
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setOrderserialno(String orderserialno) {
        this.orderserialno = orderserialno == null ? null : orderserialno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.HotelID
     *
     * @return the value of zl_rentcarorder.HotelID
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public Integer getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.HotelID
     *
     * @param hotelid the value for zl_rentcarorder.HotelID
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.HotelName
     *
     * @return the value of zl_rentcarorder.HotelName
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public String getHotelname() {
        return hotelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.HotelName
     *
     * @param hotelname the value for zl_rentcarorder.HotelName
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setHotelname(String hotelname) {
        this.hotelname = hotelname == null ? null : hotelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.RoomID
     *
     * @return the value of zl_rentcarorder.RoomID
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public Integer getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.RoomID
     *
     * @param roomid the value for zl_rentcarorder.RoomID
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.RoomNumber
     *
     * @return the value of zl_rentcarorder.RoomNumber
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public String getRoomnumber() {
        return roomnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.RoomNumber
     *
     * @param roomnumber the value for zl_rentcarorder.RoomNumber
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setRoomnumber(String roomnumber) {
        this.roomnumber = roomnumber == null ? null : roomnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.UserName
     *
     * @return the value of zl_rentcarorder.UserName
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.UserName
     *
     * @param username the value for zl_rentcarorder.UserName
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.Tel
     *
     * @return the value of zl_rentcarorder.Tel
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.Tel
     *
     * @param tel the value for zl_rentcarorder.Tel
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.OrderStatus
     *
     * @return the value of zl_rentcarorder.OrderStatus
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public Byte getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.OrderStatus
     *
     * @param orderstatus the value for zl_rentcarorder.OrderStatus
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setOrderstatus(Byte orderstatus) {
        this.orderstatus = orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.OperatorName
     *
     * @return the value of zl_rentcarorder.OperatorName
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public String getOperatorname() {
        return operatorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.OperatorName
     *
     * @param operatorname the value for zl_rentcarorder.OperatorName
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setOperatorname(String operatorname) {
        this.operatorname = operatorname == null ? null : operatorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.OperatorIP
     *
     * @return the value of zl_rentcarorder.OperatorIP
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public String getOperatorip() {
        return operatorip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.OperatorIP
     *
     * @param operatorip the value for zl_rentcarorder.OperatorIP
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setOperatorip(String operatorip) {
        this.operatorip = operatorip == null ? null : operatorip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.OperatorRemark
     *
     * @return the value of zl_rentcarorder.OperatorRemark
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public String getOperatorremark() {
        return operatorremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.OperatorRemark
     *
     * @param operatorremark the value for zl_rentcarorder.OperatorRemark
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setOperatorremark(String operatorremark) {
        this.operatorremark = operatorremark == null ? null : operatorremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.GoodsName
     *
     * @return the value of zl_rentcarorder.GoodsName
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.GoodsName
     *
     * @param goodsname the value for zl_rentcarorder.GoodsName
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname == null ? null : goodsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.CarNumber
     *
     * @return the value of zl_rentcarorder.CarNumber
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public String getCarnumber() {
        return carnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.CarNumber
     *
     * @param carnumber the value for zl_rentcarorder.CarNumber
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setCarnumber(String carnumber) {
        this.carnumber = carnumber == null ? null : carnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.RentBeginDate
     *
     * @return the value of zl_rentcarorder.RentBeginDate
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public Integer getRentbegindate() {
        return rentbegindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.RentBeginDate
     *
     * @param rentbegindate the value for zl_rentcarorder.RentBeginDate
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setRentbegindate(Integer rentbegindate) {
        this.rentbegindate = rentbegindate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.RentEndDate
     *
     * @return the value of zl_rentcarorder.RentEndDate
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public Integer getRentenddate() {
        return rentenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.RentEndDate
     *
     * @param rentenddate the value for zl_rentcarorder.RentEndDate
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setRentenddate(Integer rentenddate) {
        this.rentenddate = rentenddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.GiveBackDate
     *
     * @return the value of zl_rentcarorder.GiveBackDate
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public Integer getGivebackdate() {
        return givebackdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.GiveBackDate
     *
     * @param givebackdate the value for zl_rentcarorder.GiveBackDate
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setGivebackdate(Integer givebackdate) {
        this.givebackdate = givebackdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.RentPrice
     *
     * @return the value of zl_rentcarorder.RentPrice
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public BigDecimal getRentprice() {
        return rentprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.RentPrice
     *
     * @param rentprice the value for zl_rentcarorder.RentPrice
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setRentprice(BigDecimal rentprice) {
        this.rentprice = rentprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.RentTotalPrice
     *
     * @return the value of zl_rentcarorder.RentTotalPrice
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public BigDecimal getRenttotalprice() {
        return renttotalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.RentTotalPrice
     *
     * @param renttotalprice the value for zl_rentcarorder.RentTotalPrice
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setRenttotalprice(BigDecimal renttotalprice) {
        this.renttotalprice = renttotalprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.CanCancelOrderMinute
     *
     * @return the value of zl_rentcarorder.CanCancelOrderMinute
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public Integer getCancancelorderminute() {
        return cancancelorderminute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.CanCancelOrderMinute
     *
     * @param cancancelorderminute the value for zl_rentcarorder.CanCancelOrderMinute
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setCancancelorderminute(Integer cancancelorderminute) {
        this.cancancelorderminute = cancancelorderminute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.Remark
     *
     * @return the value of zl_rentcarorder.Remark
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.Remark
     *
     * @param remark the value for zl_rentcarorder.Remark
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.IsDelete
     *
     * @return the value of zl_rentcarorder.IsDelete
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.IsDelete
     *
     * @param isdelete the value for zl_rentcarorder.IsDelete
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.IsUserDelete
     *
     * @return the value of zl_rentcarorder.IsUserDelete
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public Boolean getIsuserdelete() {
        return isuserdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.IsUserDelete
     *
     * @param isuserdelete the value for zl_rentcarorder.IsUserDelete
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setIsuserdelete(Boolean isuserdelete) {
        this.isuserdelete = isuserdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.CreateDate
     *
     * @return the value of zl_rentcarorder.CreateDate
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public Integer getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.CreateDate
     *
     * @param createdate the value for zl_rentcarorder.CreateDate
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setCreatedate(Integer createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_rentcarorder.UpdateDate
     *
     * @return the value of zl_rentcarorder.UpdateDate
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public Integer getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_rentcarorder.UpdateDate
     *
     * @param updatedate the value for zl_rentcarorder.UpdateDate
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    public void setUpdatedate(Integer updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zl_rentcarorder
     *
     * @mbg.generated Sat Jun 06 14:09:32 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderid=").append(orderid);
        sb.append(", userid=").append(userid);
        sb.append(", orderserialno=").append(orderserialno);
        sb.append(", hotelid=").append(hotelid);
        sb.append(", hotelname=").append(hotelname);
        sb.append(", roomid=").append(roomid);
        sb.append(", roomnumber=").append(roomnumber);
        sb.append(", username=").append(username);
        sb.append(", tel=").append(tel);
        sb.append(", orderstatus=").append(orderstatus);
        sb.append(", operatorname=").append(operatorname);
        sb.append(", operatorip=").append(operatorip);
        sb.append(", operatorremark=").append(operatorremark);
        sb.append(", goodsname=").append(goodsname);
        sb.append(", carnumber=").append(carnumber);
        sb.append(", rentbegindate=").append(rentbegindate);
        sb.append(", rentenddate=").append(rentenddate);
        sb.append(", givebackdate=").append(givebackdate);
        sb.append(", rentprice=").append(rentprice);
        sb.append(", renttotalprice=").append(renttotalprice);
        sb.append(", cancancelorderminute=").append(cancancelorderminute);
        sb.append(", remark=").append(remark);
        sb.append(", isdelete=").append(isdelete);
        sb.append(", isuserdelete=").append(isuserdelete);
        sb.append(", createdate=").append(createdate);
        sb.append(", updatedate=").append(updatedate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}