package com.zhiliao.hotel.model;

import java.io.Serializable;

/**
 * 报修订单实体类
 *
 * @author null
 * @date 2020-04-14
 */
public class zlRepairorder implements Serializable {
    /**
     * 订单ID
     */
    private Long orderid;

    /**
     * 用户ID
     */
    private Long userid;

    /**
     * 订单编号
     */
    private String serialnumber;

    /**
     * 酒店ID
     */
    private Integer hotelid;

    /**
     * 酒店名
     */
    private String hotelname;

    /**
     * 房间ID
     */
    private Integer roomid;

    /**
     * 房间号
     */
    private String roomnumber;

    /**
     *  报修图片地址,多个用 | 隔开
     */
    private String imgurls;

    /**
     * 备注信息
     */
    private String remark;

    /**
     * 来自1小程序C端，2小程序B端，3公众号,4民宿，5好评返现，6分时酒店
     */
    private Integer comeformid;

    /**
     * 删除状态:0正常;1删除;
     */
    private Boolean isdelete;

    /**
     * -1:已取消;0等待确认;1已确认;2已处理
     */
    private Byte orderstatus;

    /**
     * 下单时间
     */
    private Integer createdate;

    /**
     * 支付/取消时间
     */
    private Integer updatedate;
    /**
     * 服务类型
     */
    private String fuwutype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zl_repairorder
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    private static final long serialVersionUID = 1L;
    public String getFuwutype() {
        return fuwutype;
    }

    public void setFuwutype(String fuwutype) {
        this.fuwutype = fuwutype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_repairorder.OrderID
     *
     * @return the value of zl_repairorder.OrderID
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_repairorder.OrderID
     *
     * @param orderid the value for zl_repairorder.OrderID
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_repairorder.UserID
     *
     * @return the value of zl_repairorder.UserID
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_repairorder.UserID
     *
     * @param userid the value for zl_repairorder.UserID
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_repairorder.SerialNumber
     *
     * @return the value of zl_repairorder.SerialNumber
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public String getSerialnumber() {
        return serialnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_repairorder.SerialNumber
     *
     * @param serialnumber the value for zl_repairorder.SerialNumber
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public void setSerialnumber(String serialnumber) {
        this.serialnumber = serialnumber == null ? null : serialnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_repairorder.HotelID
     *
     * @return the value of zl_repairorder.HotelID
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public Integer getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_repairorder.HotelID
     *
     * @param hotelid the value for zl_repairorder.HotelID
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_repairorder.HotelName
     *
     * @return the value of zl_repairorder.HotelName
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public String getHotelname() {
        return hotelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_repairorder.HotelName
     *
     * @param hotelname the value for zl_repairorder.HotelName
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public void setHotelname(String hotelname) {
        this.hotelname = hotelname == null ? null : hotelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_repairorder.RoomID
     *
     * @return the value of zl_repairorder.RoomID
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public Integer getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_repairorder.RoomID
     *
     * @param roomid the value for zl_repairorder.RoomID
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_repairorder.RoomNumber
     *
     * @return the value of zl_repairorder.RoomNumber
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public String getRoomnumber() {
        return roomnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_repairorder.RoomNumber
     *
     * @param roomnumber the value for zl_repairorder.RoomNumber
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public void setRoomnumber(String roomnumber) {
        this.roomnumber = roomnumber == null ? null : roomnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_repairorder.ImgUrls
     *
     * @return the value of zl_repairorder.ImgUrls
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public String getImgurls() {
        return imgurls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_repairorder.ImgUrls
     *
     * @param imgurls the value for zl_repairorder.ImgUrls
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public void setImgurls(String imgurls) {
        this.imgurls = imgurls == null ? null : imgurls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_repairorder.Remark
     *
     * @return the value of zl_repairorder.Remark
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_repairorder.Remark
     *
     * @param remark the value for zl_repairorder.Remark
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_repairorder.ComeFormID
     *
     * @return the value of zl_repairorder.ComeFormID
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public Integer getComeformid() {
        return comeformid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_repairorder.ComeFormID
     *
     * @param comeformid the value for zl_repairorder.ComeFormID
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public void setComeformid(Integer comeformid) {
        this.comeformid = comeformid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_repairorder.IsDelete
     *
     * @return the value of zl_repairorder.IsDelete
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_repairorder.IsDelete
     *
     * @param isdelete the value for zl_repairorder.IsDelete
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_repairorder.OrderStatus
     *
     * @return the value of zl_repairorder.OrderStatus
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public Byte getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_repairorder.OrderStatus
     *
     * @param orderstatus the value for zl_repairorder.OrderStatus
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public void setOrderstatus(Byte orderstatus) {
        this.orderstatus = orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_repairorder.CreateDate
     *
     * @return the value of zl_repairorder.CreateDate
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public Integer getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_repairorder.CreateDate
     *
     * @param createdate the value for zl_repairorder.CreateDate
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public void setCreatedate(Integer createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_repairorder.UpdateDate
     *
     * @return the value of zl_repairorder.UpdateDate
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public Integer getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_repairorder.UpdateDate
     *
     * @param updatedate the value for zl_repairorder.UpdateDate
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    public void setUpdatedate(Integer updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zl_repairorder
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderid=").append(orderid);
        sb.append(", userid=").append(userid);
        sb.append(", serialnumber=").append(serialnumber);
        sb.append(", hotelid=").append(hotelid);
        sb.append(", hotelname=").append(hotelname);
        sb.append(", roomid=").append(roomid);
        sb.append(", roomnumber=").append(roomnumber);
        sb.append(", imgurls=").append(imgurls);
        sb.append(", remark=").append(remark);
        sb.append(", comeformid=").append(comeformid);
        sb.append(", isdelete=").append(isdelete);
        sb.append(", orderstatus=").append(orderstatus);
        sb.append(", createdate=").append(createdate);
        sb.append(", updatedate=").append(updatedate);
        sb.append(", fuwutype=").append(fuwutype);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}