package com.zhiliao.hotel.model;

import java.io.Serializable;

/**
 * 报修信息实体类
 *
 * @author null
 * @date 2020-04-14
 */
public class zlRepair implements Serializable {
    /**
     * 维修ID
     */
    private Long repairid;

    /**
     * 用户ID
     */
    private Long userid;

    /**
     * 酒店ID
     */
    private Integer hotelid;

    /**
     * 房间ID
     */
    private Integer roomid;

    /**
     * 房间号
     */
    private String roomnumber;

    /**
     * 报修信息
     */
    private String remark;

    /**
     * 一个或多个图片地址;
     */
    private String imgurls;

    /**
     * 维状态:0未维修;1维修中;2已维修;
     */
    private Byte repairstatus;

    /**
     * 删除状态:0正常;1删除;
     */
    private Boolean isdelete;

    /**
     * 添加日期
     */
    private Integer createdate;

    /**
     * 更新日期
     */
    private Integer updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zl_repair
     *
     * @mbg.generated Tue Apr 14 10:17:21 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_repair.RepairID
     *
     * @return the value of zl_repair.RepairID
     *
     * @mbg.generated Tue Apr 14 10:17:21 CST 2020
     */
    public Long getRepairid() {
        return repairid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_repair.RepairID
     *
     * @param repairid the value for zl_repair.RepairID
     *
     * @mbg.generated Tue Apr 14 10:17:21 CST 2020
     */
    public void setRepairid(Long repairid) {
        this.repairid = repairid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_repair.UserID
     *
     * @return the value of zl_repair.UserID
     *
     * @mbg.generated Tue Apr 14 10:17:21 CST 2020
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_repair.UserID
     *
     * @param userid the value for zl_repair.UserID
     *
     * @mbg.generated Tue Apr 14 10:17:21 CST 2020
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_repair.HotelID
     *
     * @return the value of zl_repair.HotelID
     *
     * @mbg.generated Tue Apr 14 10:17:21 CST 2020
     */
    public Integer getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_repair.HotelID
     *
     * @param hotelid the value for zl_repair.HotelID
     *
     * @mbg.generated Tue Apr 14 10:17:21 CST 2020
     */
    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_repair.RoomID
     *
     * @return the value of zl_repair.RoomID
     *
     * @mbg.generated Tue Apr 14 10:17:21 CST 2020
     */
    public Integer getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_repair.RoomID
     *
     * @param roomid the value for zl_repair.RoomID
     *
     * @mbg.generated Tue Apr 14 10:17:21 CST 2020
     */
    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_repair.RoomNumber
     *
     * @return the value of zl_repair.RoomNumber
     *
     * @mbg.generated Tue Apr 14 10:17:21 CST 2020
     */
    public String getRoomnumber() {
        return roomnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_repair.RoomNumber
     *
     * @param roomnumber the value for zl_repair.RoomNumber
     *
     * @mbg.generated Tue Apr 14 10:17:21 CST 2020
     */
    public void setRoomnumber(String roomnumber) {
        this.roomnumber = roomnumber == null ? null : roomnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_repair.Remark
     *
     * @return the value of zl_repair.Remark
     *
     * @mbg.generated Tue Apr 14 10:17:21 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_repair.Remark
     *
     * @param remark the value for zl_repair.Remark
     *
     * @mbg.generated Tue Apr 14 10:17:21 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_repair.ImgUrls
     *
     * @return the value of zl_repair.ImgUrls
     *
     * @mbg.generated Tue Apr 14 10:17:21 CST 2020
     */
    public String getImgurls() {
        return imgurls;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_repair.ImgUrls
     *
     * @param imgurls the value for zl_repair.ImgUrls
     *
     * @mbg.generated Tue Apr 14 10:17:21 CST 2020
     */
    public void setImgurls(String imgurls) {
        this.imgurls = imgurls == null ? null : imgurls.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_repair.RepairStatus
     *
     * @return the value of zl_repair.RepairStatus
     *
     * @mbg.generated Tue Apr 14 10:17:21 CST 2020
     */
    public Byte getRepairstatus() {
        return repairstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_repair.RepairStatus
     *
     * @param repairstatus the value for zl_repair.RepairStatus
     *
     * @mbg.generated Tue Apr 14 10:17:21 CST 2020
     */
    public void setRepairstatus(Byte repairstatus) {
        this.repairstatus = repairstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_repair.IsDelete
     *
     * @return the value of zl_repair.IsDelete
     *
     * @mbg.generated Tue Apr 14 10:17:21 CST 2020
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_repair.IsDelete
     *
     * @param isdelete the value for zl_repair.IsDelete
     *
     * @mbg.generated Tue Apr 14 10:17:21 CST 2020
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_repair.CreateDate
     *
     * @return the value of zl_repair.CreateDate
     *
     * @mbg.generated Tue Apr 14 10:17:21 CST 2020
     */
    public Integer getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_repair.CreateDate
     *
     * @param createdate the value for zl_repair.CreateDate
     *
     * @mbg.generated Tue Apr 14 10:17:21 CST 2020
     */
    public void setCreatedate(Integer createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_repair.UpdateDate
     *
     * @return the value of zl_repair.UpdateDate
     *
     * @mbg.generated Tue Apr 14 10:17:21 CST 2020
     */
    public Integer getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_repair.UpdateDate
     *
     * @param updatedate the value for zl_repair.UpdateDate
     *
     * @mbg.generated Tue Apr 14 10:17:21 CST 2020
     */
    public void setUpdatedate(Integer updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zl_repair
     *
     * @mbg.generated Tue Apr 14 10:17:21 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", repairid=").append(repairid);
        sb.append(", userid=").append(userid);
        sb.append(", hotelid=").append(hotelid);
        sb.append(", roomid=").append(roomid);
        sb.append(", roomnumber=").append(roomnumber);
        sb.append(", remark=").append(remark);
        sb.append(", imgurls=").append(imgurls);
        sb.append(", repairstatus=").append(repairstatus);
        sb.append(", isdelete=").append(isdelete);
        sb.append(", createdate=").append(createdate);
        sb.append(", updatedate=").append(updatedate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}