package com.zhiliao.hotel.model;

import java.io.Serializable;

/**
 * 报修订单实体类
 *
 * @author null
 * @date 2020-04-14
 */
public class ZlRepairorder implements Serializable {
    /**
     * 订单ID
     */
    private Long orderid;

    /**
     * 用户ID
     */
    private Long userid;

    /**
     * 订单编号
     */
    private String serialnumber;

    /**
     * 酒店ID
     */
    private Integer hotelid;

    /**
     * 酒店名
     */
    private String hotelname;

    /**
     * 房间ID
     */
    private Integer roomid;

    /**
     * 房间号
     */
    private String roomnumber;

    /**
     *  报修图片地址,多个用 | 隔开
     */
    private String imgurls;

    /**
     * 备注信息
     */
    private String remark;

    /**
     * 来自1小程序C端，2小程序B端，3公众号,4民宿，5好评返现，6分时酒店
     */
    private Integer comeformid;

    /**
     * 删除状态:0正常;1删除;
     */
    private Boolean isdelete;

    /**
     * -1:已取消;0等待确认;1已确认;2已处理
     */
    private Byte orderstatus;

    /**
     * 下单时间
     */
    private Integer createdate;

    /**
     * 支付/取消时间
     */
    private Integer updatedate;
    /**
     * 服务类型
     */
    private String fuwutype;


    /**
     * 预约时间
     */
    private Integer appointmentdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zl_repairorder
     *
     * @mbg.generated Tue Apr 14 10:16:55 CST 2020
     */
    private static final long serialVersionUID = 1L;


    @Override
    public String toString() {
        return "ZlRepairorder{" +
                "orderid=" + orderid +
                ", userid=" + userid +
                ", serialnumber='" + serialnumber + '\'' +
                ", hotelid=" + hotelid +
                ", hotelname='" + hotelname + '\'' +
                ", roomid=" + roomid +
                ", roomnumber='" + roomnumber + '\'' +
                ", imgurls='" + imgurls + '\'' +
                ", remark='" + remark + '\'' +
                ", comeformid=" + comeformid +
                ", isdelete=" + isdelete +
                ", orderstatus=" + orderstatus +
                ", createdate=" + createdate +
                ", updatedate=" + updatedate +
                ", fuwutype='" + fuwutype + '\'' +
                ", appointmentdate=" + appointmentdate +
                '}';
    }

    public Long getOrderid() {
        return orderid;
    }

    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    public Long getUserid() {
        return userid;
    }

    public void setUserid(Long userid) {
        this.userid = userid;
    }

    public String getSerialnumber() {
        return serialnumber;
    }

    public void setSerialnumber(String serialnumber) {
        this.serialnumber = serialnumber;
    }

    public Integer getHotelid() {
        return hotelid;
    }

    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    public String getHotelname() {
        return hotelname;
    }

    public void setHotelname(String hotelname) {
        this.hotelname = hotelname;
    }

    public Integer getRoomid() {
        return roomid;
    }

    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }

    public String getRoomnumber() {
        return roomnumber;
    }

    public void setRoomnumber(String roomnumber) {
        this.roomnumber = roomnumber;
    }

    public String getImgurls() {
        return imgurls;
    }

    public void setImgurls(String imgurls) {
        this.imgurls = imgurls;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Integer getComeformid() {
        return comeformid;
    }

    public void setComeformid(Integer comeformid) {
        this.comeformid = comeformid;
    }

    public Boolean getIsdelete() {
        return isdelete;
    }

    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    public Byte getOrderstatus() {
        return orderstatus;
    }

    public void setOrderstatus(Byte orderstatus) {
        this.orderstatus = orderstatus;
    }

    public Integer getCreatedate() {
        return createdate;
    }

    public void setCreatedate(Integer createdate) {
        this.createdate = createdate;
    }

    public Integer getUpdatedate() {
        return updatedate;
    }

    public void setUpdatedate(Integer updatedate) {
        this.updatedate = updatedate;
    }

    public String getFuwutype() {
        return fuwutype;
    }

    public void setFuwutype(String fuwutype) {
        this.fuwutype = fuwutype;
    }

    public Integer getAppointmentdate() {
        return appointmentdate;
    }

    public void setAppointmentdate(Integer appointmentdate) {
        this.appointmentdate = appointmentdate;
    }

    public static long getSerialVersionUID() {
        return serialVersionUID;
    }
}