package com.zhiliao.hotel.model;

import java.io.Serializable;

/**
 *  扫码率
 *
 * @author denghanchen
 * @date 2020-04-14
 */
public class ZlUserloginlog implements Serializable {
    /**
     * 
     */
    private Long userloginlogid;

    /**
     * 用户ID
     */
    private Long userid;

    /**
     * 用户昵称
     */
    private String nickname;

    /**
     * 酒店ID
     */
    private Integer hotelid;

    /**
     * 酒店名
     */
    private String hotelname;

    /**
     * 房间ID
     */
    private Integer roomid;

    /**
     * 房间名
     */
    private String roomnumber;

    /**
     * 登录IP
     */
    private String loginip;

    /**
     * 渠道来源:
     */
    private Byte comefromid;

    /**
     * 创建时间(登录时间)
     */
    private Long createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zl_userloginlog
     *
     * @mbg.generated Tue Apr 14 11:28:55 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_userloginlog.UserLoginLogID
     *
     * @return the value of zl_userloginlog.UserLoginLogID
     *
     * @mbg.generated Tue Apr 14 11:28:55 CST 2020
     */
    public Long getUserloginlogid() {
        return userloginlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_userloginlog.UserLoginLogID
     *
     * @param userloginlogid the value for zl_userloginlog.UserLoginLogID
     *
     * @mbg.generated Tue Apr 14 11:28:55 CST 2020
     */
    public void setUserloginlogid(Long userloginlogid) {
        this.userloginlogid = userloginlogid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_userloginlog.UserID
     *
     * @return the value of zl_userloginlog.UserID
     *
     * @mbg.generated Tue Apr 14 11:28:55 CST 2020
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_userloginlog.UserID
     *
     * @param userid the value for zl_userloginlog.UserID
     *
     * @mbg.generated Tue Apr 14 11:28:55 CST 2020
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_userloginlog.NickName
     *
     * @return the value of zl_userloginlog.NickName
     *
     * @mbg.generated Tue Apr 14 11:28:55 CST 2020
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_userloginlog.NickName
     *
     * @param nickname the value for zl_userloginlog.NickName
     *
     * @mbg.generated Tue Apr 14 11:28:55 CST 2020
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_userloginlog.HotelID
     *
     * @return the value of zl_userloginlog.HotelID
     *
     * @mbg.generated Tue Apr 14 11:28:55 CST 2020
     */
    public Integer getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_userloginlog.HotelID
     *
     * @param hotelid the value for zl_userloginlog.HotelID
     *
     * @mbg.generated Tue Apr 14 11:28:55 CST 2020
     */
    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_userloginlog.HotelName
     *
     * @return the value of zl_userloginlog.HotelName
     *
     * @mbg.generated Tue Apr 14 11:28:55 CST 2020
     */
    public String getHotelname() {
        return hotelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_userloginlog.HotelName
     *
     * @param hotelname the value for zl_userloginlog.HotelName
     *
     * @mbg.generated Tue Apr 14 11:28:55 CST 2020
     */
    public void setHotelname(String hotelname) {
        this.hotelname = hotelname == null ? null : hotelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_userloginlog.RoomID
     *
     * @return the value of zl_userloginlog.RoomID
     *
     * @mbg.generated Tue Apr 14 11:28:55 CST 2020
     */
    public Integer getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_userloginlog.RoomID
     *
     * @param roomid the value for zl_userloginlog.RoomID
     *
     * @mbg.generated Tue Apr 14 11:28:55 CST 2020
     */
    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_userloginlog.RoomNumber
     *
     * @return the value of zl_userloginlog.RoomNumber
     *
     * @mbg.generated Tue Apr 14 11:28:55 CST 2020
     */
    public String getRoomnumber() {
        return roomnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_userloginlog.RoomNumber
     *
     * @param roomnumber the value for zl_userloginlog.RoomNumber
     *
     * @mbg.generated Tue Apr 14 11:28:55 CST 2020
     */
    public void setRoomnumber(String roomnumber) {
        this.roomnumber = roomnumber == null ? null : roomnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_userloginlog.LoginIP
     *
     * @return the value of zl_userloginlog.LoginIP
     *
     * @mbg.generated Tue Apr 14 11:28:55 CST 2020
     */
    public String getLoginip() {
        return loginip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_userloginlog.LoginIP
     *
     * @param loginip the value for zl_userloginlog.LoginIP
     *
     * @mbg.generated Tue Apr 14 11:28:55 CST 2020
     */
    public void setLoginip(String loginip) {
        this.loginip = loginip == null ? null : loginip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_userloginlog.ComeFromID
     *
     * @return the value of zl_userloginlog.ComeFromID
     *
     * @mbg.generated Tue Apr 14 11:28:55 CST 2020
     */
    public Byte getComefromid() {
        return comefromid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_userloginlog.ComeFromID
     *
     * @param comefromid the value for zl_userloginlog.ComeFromID
     *
     * @mbg.generated Tue Apr 14 11:28:55 CST 2020
     */
    public void setComefromid(Byte comefromid) {
        this.comefromid = comefromid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_userloginlog.CreateDate
     *
     * @return the value of zl_userloginlog.CreateDate
     *
     * @mbg.generated Tue Apr 14 11:28:55 CST 2020
     */
    public Long getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_userloginlog.CreateDate
     *
     * @param createdate the value for zl_userloginlog.CreateDate
     *
     * @mbg.generated Tue Apr 14 11:28:55 CST 2020
     */
    public void setCreatedate(Long createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zl_userloginlog
     *
     * @mbg.generated Tue Apr 14 11:28:55 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", userloginlogid=").append(userloginlogid);
        sb.append(", userid=").append(userid);
        sb.append(", nickname=").append(nickname);
        sb.append(", hotelid=").append(hotelid);
        sb.append(", hotelname=").append(hotelname);
        sb.append(", roomid=").append(roomid);
        sb.append(", roomnumber=").append(roomnumber);
        sb.append(", loginip=").append(loginip);
        sb.append(", comefromid=").append(comefromid);
        sb.append(", createdate=").append(createdate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}