package com.zhiliao.hotel.model;

import org.springframework.data.annotation.Id;

import javax.persistence.GeneratedValue;
import javax.persistence.Table;
import java.io.Serializable;

/**
 * 
 *
 * @author null
 * @date 2020-06-05
 */
@Table(name = "zl_wakeorder")
public class ZlWakeOrder implements Serializable {
    /**
     * 订单ID
     */
    @Id
    @GeneratedValue(generator = "JDBC")
    private Long orderid;

    /**
     * 用户ID
     */
    private Long userid;

    /**
     * 订单编号
     */
    private String orderserialno;

    /**
     * 酒店ID
     */
    private Integer hotelid;

    /**
     * 酒店名
     */
    private String hotelname;

    /**
     * 房间ID
     */
    private Integer roomid;

    /**
     * 房间号
     */
    private String roomnumber;

    /**
     * 用户名
     */
    private String username;

    /**
     * 手机
     */
    private String tel;

    /**
     * 订单状态:-1:已取消;0待处理;1处理完成
     */
    private Byte orderstatus;

    /**
     * 操作员
     */
    private String operatorname;

    /**
     * 操作员IP
     */
    private String operatorip;

    /**
     * 操作员备注
     */
    private String operatorremark;

    /**
     * 叫醒时间
     */
    private Integer wakedate;

    /**
     * 备注
     */
    private String remark;

    /**
     * 删除状态:0正常;1删除;
     */
    private Boolean isdelete;

    /**
     * 用户删除:0否;1是
     */
    private Boolean isuserdelete;

    /**
     * 创建时间（下单时间)
     */
    private Integer createdate;

    /**
     * 修改时间（操作时间）
     */
    private Integer updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zl_wakeorder
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_wakeorder.OrderID
     *
     * @return the value of zl_wakeorder.OrderID
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public Long getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_wakeorder.OrderID
     *
     * @param orderid the value for zl_wakeorder.OrderID
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public void setOrderid(Long orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_wakeorder.UserID
     *
     * @return the value of zl_wakeorder.UserID
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public Long getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_wakeorder.UserID
     *
     * @param userid the value for zl_wakeorder.UserID
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public void setUserid(Long userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_wakeorder.OrderSerialNo
     *
     * @return the value of zl_wakeorder.OrderSerialNo
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public String getOrderserialno() {
        return orderserialno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_wakeorder.OrderSerialNo
     *
     * @param orderserialno the value for zl_wakeorder.OrderSerialNo
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public void setOrderserialno(String orderserialno) {
        this.orderserialno = orderserialno == null ? null : orderserialno.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_wakeorder.HotelID
     *
     * @return the value of zl_wakeorder.HotelID
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public Integer getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_wakeorder.HotelID
     *
     * @param hotelid the value for zl_wakeorder.HotelID
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_wakeorder.HotelName
     *
     * @return the value of zl_wakeorder.HotelName
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public String getHotelname() {
        return hotelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_wakeorder.HotelName
     *
     * @param hotelname the value for zl_wakeorder.HotelName
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public void setHotelname(String hotelname) {
        this.hotelname = hotelname == null ? null : hotelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_wakeorder.RoomID
     *
     * @return the value of zl_wakeorder.RoomID
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public Integer getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_wakeorder.RoomID
     *
     * @param roomid the value for zl_wakeorder.RoomID
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public void setRoomid(Integer roomid) {
        this.roomid = roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_wakeorder.RoomNumber
     *
     * @return the value of zl_wakeorder.RoomNumber
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public String getRoomnumber() {
        return roomnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_wakeorder.RoomNumber
     *
     * @param roomnumber the value for zl_wakeorder.RoomNumber
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public void setRoomnumber(String roomnumber) {
        this.roomnumber = roomnumber == null ? null : roomnumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_wakeorder.UserName
     *
     * @return the value of zl_wakeorder.UserName
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_wakeorder.UserName
     *
     * @param username the value for zl_wakeorder.UserName
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_wakeorder.Tel
     *
     * @return the value of zl_wakeorder.Tel
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_wakeorder.Tel
     *
     * @param tel the value for zl_wakeorder.Tel
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_wakeorder.OrderStatus
     *
     * @return the value of zl_wakeorder.OrderStatus
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public Byte getOrderstatus() {
        return orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_wakeorder.OrderStatus
     *
     * @param orderstatus the value for zl_wakeorder.OrderStatus
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public void setOrderstatus(Byte orderstatus) {
        this.orderstatus = orderstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_wakeorder.OperatorName
     *
     * @return the value of zl_wakeorder.OperatorName
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public String getOperatorname() {
        return operatorname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_wakeorder.OperatorName
     *
     * @param operatorname the value for zl_wakeorder.OperatorName
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public void setOperatorname(String operatorname) {
        this.operatorname = operatorname == null ? null : operatorname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_wakeorder.OperatorIP
     *
     * @return the value of zl_wakeorder.OperatorIP
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public String getOperatorip() {
        return operatorip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_wakeorder.OperatorIP
     *
     * @param operatorip the value for zl_wakeorder.OperatorIP
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public void setOperatorip(String operatorip) {
        this.operatorip = operatorip == null ? null : operatorip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_wakeorder.OperatorRemark
     *
     * @return the value of zl_wakeorder.OperatorRemark
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public String getOperatorremark() {
        return operatorremark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_wakeorder.OperatorRemark
     *
     * @param operatorremark the value for zl_wakeorder.OperatorRemark
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public void setOperatorremark(String operatorremark) {
        this.operatorremark = operatorremark == null ? null : operatorremark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_wakeorder.WakeDate
     *
     * @return the value of zl_wakeorder.WakeDate
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public Integer getWakedate() {
        return wakedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_wakeorder.WakeDate
     *
     * @param wakedate the value for zl_wakeorder.WakeDate
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public void setWakedate(Integer wakedate) {
        this.wakedate = wakedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_wakeorder.Remark
     *
     * @return the value of zl_wakeorder.Remark
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_wakeorder.Remark
     *
     * @param remark the value for zl_wakeorder.Remark
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_wakeorder.IsDelete
     *
     * @return the value of zl_wakeorder.IsDelete
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_wakeorder.IsDelete
     *
     * @param isdelete the value for zl_wakeorder.IsDelete
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_wakeorder.IsUserDelete
     *
     * @return the value of zl_wakeorder.IsUserDelete
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public Boolean getIsuserdelete() {
        return isuserdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_wakeorder.IsUserDelete
     *
     * @param isuserdelete the value for zl_wakeorder.IsUserDelete
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public void setIsuserdelete(Boolean isuserdelete) {
        this.isuserdelete = isuserdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_wakeorder.CreateDate
     *
     * @return the value of zl_wakeorder.CreateDate
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public Integer getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_wakeorder.CreateDate
     *
     * @param createdate the value for zl_wakeorder.CreateDate
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public void setCreatedate(Integer createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_wakeorder.UpdateDate
     *
     * @return the value of zl_wakeorder.UpdateDate
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public Integer getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_wakeorder.UpdateDate
     *
     * @param updatedate the value for zl_wakeorder.UpdateDate
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    public void setUpdatedate(Integer updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zl_wakeorder
     *
     * @mbg.generated Fri Jun 05 15:35:55 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderid=").append(orderid);
        sb.append(", userid=").append(userid);
        sb.append(", orderserialno=").append(orderserialno);
        sb.append(", hotelid=").append(hotelid);
        sb.append(", hotelname=").append(hotelname);
        sb.append(", roomid=").append(roomid);
        sb.append(", roomnumber=").append(roomnumber);
        sb.append(", username=").append(username);
        sb.append(", tel=").append(tel);
        sb.append(", orderstatus=").append(orderstatus);
        sb.append(", operatorname=").append(operatorname);
        sb.append(", operatorip=").append(operatorip);
        sb.append(", operatorremark=").append(operatorremark);
        sb.append(", wakedate=").append(wakedate);
        sb.append(", remark=").append(remark);
        sb.append(", isdelete=").append(isdelete);
        sb.append(", isuserdelete=").append(isuserdelete);
        sb.append(", createdate=").append(createdate);
        sb.append(", updatedate=").append(updatedate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}