package com.zhiliao.hotel.model;

import java.io.Serializable;

/**
 * 酒店小程序菜单
 *
 * @author denghanchen
 * @date 2020-04-14
 */
public class ZlXcxmenu implements Serializable {
    /**
     * 
     */
    private Short id;

    /**
     * 酒店ID:为0时表示平台;
     */
    private Integer hotelid;

    /**
     * 菜单栏ID
     */
    private Integer menuid;

    /**
     * 功能菜单名称
     */
    private String menuname;

    /**
     * Url地址
     */
    private String linkurl;

    /**
     * 图标
     */
    private String iconurl;

    /**
     * 0:无;1有
     */
    private Boolean havebanner;

    /**
     * 服务时间段
     */
    private String serviceopentime;

    /**
     * 排序
     */
    private Integer sort;

    /**
     * 状态:-1禁用;1启用
     */
    private Boolean menustatus;

    /**
     * 小程序渠道：1C端，2B端
     */
    private Byte comefromid;

    /**
     * 删除状态:0正常;1删除;
     */
    private Boolean isdelete;

    /**
     * 添加时间
     */
    private Integer createdate;

    /**
     * 修改时间
     */
    private Integer updatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zl_xcxmenu
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_xcxmenu.ID
     *
     * @return the value of zl_xcxmenu.ID
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_xcxmenu.ID
     *
     * @param id the value for zl_xcxmenu.ID
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_xcxmenu.HotelID
     *
     * @return the value of zl_xcxmenu.HotelID
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public Integer getHotelid() {
        return hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_xcxmenu.HotelID
     *
     * @param hotelid the value for zl_xcxmenu.HotelID
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public void setHotelid(Integer hotelid) {
        this.hotelid = hotelid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_xcxmenu.MenuID
     *
     * @return the value of zl_xcxmenu.MenuID
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public Integer getMenuid() {
        return menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_xcxmenu.MenuID
     *
     * @param menuid the value for zl_xcxmenu.MenuID
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public void setMenuid(Integer menuid) {
        this.menuid = menuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_xcxmenu.MenuName
     *
     * @return the value of zl_xcxmenu.MenuName
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public String getMenuname() {
        return menuname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_xcxmenu.MenuName
     *
     * @param menuname the value for zl_xcxmenu.MenuName
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public void setMenuname(String menuname) {
        this.menuname = menuname == null ? null : menuname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_xcxmenu.LinkUrl
     *
     * @return the value of zl_xcxmenu.LinkUrl
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public String getLinkurl() {
        return linkurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_xcxmenu.LinkUrl
     *
     * @param linkurl the value for zl_xcxmenu.LinkUrl
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public void setLinkurl(String linkurl) {
        this.linkurl = linkurl == null ? null : linkurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_xcxmenu.IconUrl
     *
     * @return the value of zl_xcxmenu.IconUrl
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public String getIconurl() {
        return iconurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_xcxmenu.IconUrl
     *
     * @param iconurl the value for zl_xcxmenu.IconUrl
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public void setIconurl(String iconurl) {
        this.iconurl = iconurl == null ? null : iconurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_xcxmenu.HaveBanner
     *
     * @return the value of zl_xcxmenu.HaveBanner
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public Boolean getHavebanner() {
        return havebanner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_xcxmenu.HaveBanner
     *
     * @param havebanner the value for zl_xcxmenu.HaveBanner
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public void setHavebanner(Boolean havebanner) {
        this.havebanner = havebanner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_xcxmenu.ServiceOpenTime
     *
     * @return the value of zl_xcxmenu.ServiceOpenTime
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public String getServiceopentime() {
        return serviceopentime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_xcxmenu.ServiceOpenTime
     *
     * @param serviceopentime the value for zl_xcxmenu.ServiceOpenTime
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public void setServiceopentime(String serviceopentime) {
        this.serviceopentime = serviceopentime == null ? null : serviceopentime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_xcxmenu.Sort
     *
     * @return the value of zl_xcxmenu.Sort
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_xcxmenu.Sort
     *
     * @param sort the value for zl_xcxmenu.Sort
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_xcxmenu.MenuStatus
     *
     * @return the value of zl_xcxmenu.MenuStatus
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public Boolean getMenustatus() {
        return menustatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_xcxmenu.MenuStatus
     *
     * @param menustatus the value for zl_xcxmenu.MenuStatus
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public void setMenustatus(Boolean menustatus) {
        this.menustatus = menustatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_xcxmenu.ComeFromID
     *
     * @return the value of zl_xcxmenu.ComeFromID
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public Byte getComefromid() {
        return comefromid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_xcxmenu.ComeFromID
     *
     * @param comefromid the value for zl_xcxmenu.ComeFromID
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public void setComefromid(Byte comefromid) {
        this.comefromid = comefromid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_xcxmenu.IsDelete
     *
     * @return the value of zl_xcxmenu.IsDelete
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public Boolean getIsdelete() {
        return isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_xcxmenu.IsDelete
     *
     * @param isdelete the value for zl_xcxmenu.IsDelete
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public void setIsdelete(Boolean isdelete) {
        this.isdelete = isdelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_xcxmenu.CreateDate
     *
     * @return the value of zl_xcxmenu.CreateDate
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public Integer getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_xcxmenu.CreateDate
     *
     * @param createdate the value for zl_xcxmenu.CreateDate
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public void setCreatedate(Integer createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_xcxmenu.UpdateDate
     *
     * @return the value of zl_xcxmenu.UpdateDate
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public Integer getUpdatedate() {
        return updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zl_xcxmenu.UpdateDate
     *
     * @param updatedate the value for zl_xcxmenu.UpdateDate
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    public void setUpdatedate(Integer updatedate) {
        this.updatedate = updatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zl_xcxmenu
     *
     * @mbg.generated Tue Apr 14 11:13:59 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", hotelid=").append(hotelid);
        sb.append(", menuid=").append(menuid);
        sb.append(", menuname=").append(menuname);
        sb.append(", linkurl=").append(linkurl);
        sb.append(", iconurl=").append(iconurl);
        sb.append(", havebanner=").append(havebanner);
        sb.append(", serviceopentime=").append(serviceopentime);
        sb.append(", sort=").append(sort);
        sb.append(", menustatus=").append(menustatus);
        sb.append(", comefromid=").append(comefromid);
        sb.append(", isdelete=").append(isdelete);
        sb.append(", createdate=").append(createdate);
        sb.append(", updatedate=").append(updatedate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}