package com.zhiliao.hotel.controller.hotel.in;

import com.zhiliao.hotel.model.ZlBanner;
import com.zhiliao.hotel.model.ZlHotelroom;
import com.zhiliao.hotel.model.ZlXcxmenu;
import lombok.Getter;
import lombok.Setter;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;
import  com.zhiliao.hotel.model.zlNews;

/**
 * @chenrong
 * @created 2020/4/17
 */
@Getter
@Setter
public class ZlHotelIn implements Serializable {


    /**
     *  酒店ID
     */
    private Integer hotelid;

    /**
     * 酒店名称
     */
    private String hotelname;

    /**
     *
     */
    private String coverurl;

    /**
     * 客服电话, 多个用|隔开
     */
    private String tel;

    /**
     * 省编号(对应area表AreaID)
     */
    private Short provincecode;

    /**
     * 市编号(对应area表)
     */
    private Short citycode;

    /**
     * 区编号(对应area表)
     */
    private Short districtcode;

    /**
     * 酒店详细地址
     */
    private String address;

    /**
     * 最大允许挂账金额
     */
    private BigDecimal maxcreditcash;

    /**
     * 类型:1酒店;2民宿
     */
    private Byte hoteltype;

    /**
     * 酒店状态:0关闭;1启用
     */
    private Boolean hotelstatus;

    /**
     * 经度
     */
    private Float longitude;

    /**
     * 纬度
     */
    private Float latitude;

    /**
     * 结算方式 百分比
     */
    private Float settlement;

    /**
     * 起送金额
     */
    private Long minsendcash;

    /**
     * 配送金额
     */
    private Long sendcash;

    /**
     * 合约图片,存储多个
     */
    private String contractimgurls;

    /**
     * 开户行
     */
    private String bank;

    /**
     * 开户行账号
     */
    private String bankaccountnumber;

    /**
     * 户名
     */
    private String bankaccountname;

    /**
     * 今天的利润
     */
    private BigDecimal todaymoney;

    /**
     * 总可提现的利润
     */
    private BigDecimal allmoney;

    /**
     * 天气设置
     */
    private String weather;

    /**
     * 是否是S2入驻，0不是，其他S2ID
     */
    private Integer isjoins2;

    /**
     * 删除状态:0正常;1删除;
     */
    private Boolean isdelete;

    /**
     * 更新日期
     */
    private Integer updatedate;

    /**
     * 添加日期
     */
    private Integer createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zl_hotel
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zl_hotel.HotelID
     *
     * @return the value of zl_hotel.HotelID
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */


    /**
     * banner集合
     */
    private List<ZlBanner> zlBannerList;

    /**
     * 菜单集合
     */
    private List<ZlXcxmenu>zlXcxmenus;

    /**
     * 酒店客房信息
     */
    private ZlHotelroom hotelroom;

    /**
     * 酒店公告信息
     */
    private List<zlNews> zlNews;

}
