package com.zhiliao.hotel.controller.hotel.in;

import com.zhiliao.hotel.model.*;
import org.springframework.beans.BeanUtils;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

/**
 * @chenrong
 * @created 2020/4/17
 */

public class ZlHotelIn implements Serializable {

    private String receptionTel;

    public String getReceptionTel() {
        return receptionTel;
    }

    public void setReceptionTel(String receptionTel) {
        this.receptionTel = receptionTel;
    }

    public ZlHotelIn(){
        super();
    }

    public ZlHotelIn(ZlHotel zlHotel){
        BeanUtils.copyProperties(zlHotel,this);
    }

    public Integer getHotelID() {
        return hotelID;
    }

    public void setHotelID(Integer hotelID) {
        this.hotelID = hotelID;
    }

    private Integer hotelID;

    /**
     * 酒店名称
     */
    private String hotelName;

    /**
     *
     */
    private String coverUrl;

    /**
     * 客服电话, 多个用|隔开
     */
    private String tel;

    /**
     * 省编号(对应area表AreaID)
     */
    private Short provinceCode;

    /**
     * 市编号(对应area表)
     */
    private Short cityCode;

    /**
     * 区编号(对应area表)
     */
    private Short districtCode;

    /**
     * 酒店详细地址
     */
    private String address;

    /**
     * 最大允许挂账金额
     */
    private BigDecimal maxCreditCash;

    /**
     * 类型:1酒店;2民宿
     */
    private Byte hotelType;

    /**
     * 酒店状态:0关闭;1启用
     */
    private Boolean hotelStatus;

    /**
     * 今天的利润
     */
    private BigDecimal todayMoney;
    /**
     * 累计获得佣金
     */
    private BigDecimal allMoney;

    /**
     * 已提现佣金
     */
    private BigDecimal withdrewMoney;
    /**
     * 提现处理中佣金
     */
    private BigDecimal withdrawingMoney;

    /**
     * 入驻类型：0：非入驻型；1：酒店自己入驻；2：通过S2入驻
     */
    private Integer joinType;

    /**
     * 入驻酒店合作状态：-1终止合作;1已正常入驻
     */
    private Integer joinStatus;


    /**
     * 删除状态:0正常;1删除;
     */
    private Boolean isDelete;

    /**
     * 更新日期
     */
    private Integer updateDate;

    /**
     * 添加日期
     */
    private Integer createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table zl_hotel
     *
     * @mbg.generated Tue Apr 14 11:22:18 CST 2020
     */
    private static final long serialVersionUID = 1L;


    private List<ZlBanner>zlBannerList;

    public List<ZlBanner> getZlBannerList() {
        return zlBannerList;
    }

    public void setZlBannerList(List<ZlBanner> zlBannerList) {
        this.zlBannerList = zlBannerList;
    }

    public List<ZlXcxmenu> getZlXcxMenus() {
        return zlXcxMenus;
    }

    public void setZlXcxMenus(List<ZlXcxmenu> zlXcxMenus) {
        this.zlXcxMenus = zlXcxMenus;
    }

    public ZlHotelroom getHotelRoom() {
        return hotelRoom;
    }

    public void setHotelRoom(ZlHotelroom hotelRoom) {
        this.hotelRoom = hotelRoom;
    }

    private List<ZlXcxmenu>zlXcxMenus;

    private ZlHotelroom  hotelRoom;



    public String getHotelName() {
        return hotelName;
    }

    public void setHotelName(String hotelName) {
        this.hotelName = hotelName;
    }

    public String getCoverUrl() {
        return coverUrl;
    }

    public void setCoverUrl(String coverUrl) {
        this.coverUrl = coverUrl;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public Short getProvinceCode() {
        return provinceCode;
    }

    public void setProvinceCode(Short provinceCode) {
        this.provinceCode = provinceCode;
    }

    public Short getCityCode() {
        return cityCode;
    }

    public void setCityCode(Short cityCode) {
        this.cityCode = cityCode;
    }

    public Short getDistrictCode() {
        return districtCode;
    }

    public void setDistrictCode(Short districtCode) {
        this.districtCode = districtCode;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public BigDecimal getMaxCreditCash() {
        return maxCreditCash;
    }

    public void setMaxCreditCash(BigDecimal maxCreditCash) {
        this.maxCreditCash = maxCreditCash;
    }

    public Byte getHotelType() {
        return hotelType;
    }

    public void setHotelType(Byte hotelType) {
        this.hotelType = hotelType;
    }

    public Boolean getHotelStatus() {
        return hotelStatus;
    }

    public void setHotelStatus(Boolean hotelStatus) {
        this.hotelStatus = hotelStatus;
    }

    public BigDecimal getTodayMoney() {
        return todayMoney;
    }

    public void setTodayMoney(BigDecimal todayMoney) {
        this.todayMoney = todayMoney;
    }

    public BigDecimal getAllMoney() {
        return allMoney;
    }

    public void setAllMoney(BigDecimal allMoney) {
        this.allMoney = allMoney;
    }

    public BigDecimal getWithdrewMoney() {
        return withdrewMoney;
    }

    public void setWithdrewMoney(BigDecimal withdrewMoney) {
        this.withdrewMoney = withdrewMoney;
    }

    public BigDecimal getWithdrawingMoney() {
        return withdrawingMoney;
    }

    public void setWithdrawingMoney(BigDecimal withdrawingMoney) {
        this.withdrawingMoney = withdrawingMoney;
    }

    public Integer getJoinType() {
        return joinType;
    }

    public void setJoinType(Integer joinType) {
        this.joinType = joinType;
    }

    public Integer getJoinStatus() {
        return joinStatus;
    }

    public void setJoinStatus(Integer joinStatus) {
        this.joinStatus = joinStatus;
    }

    public Boolean getDelete() {
        return isDelete;
    }

    public void setDelete(Boolean delete) {
        isDelete = delete;
    }

    public Integer getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(Integer updateDate) {
        this.updateDate = updateDate;
    }

    public Integer getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Integer createDate) {
        this.createDate = createDate;
    }

    public List<ZlNews> getZlNews() {
        return zlNews;
    }

    public void setZlNews(List<ZlNews> zlNews) {
        this.zlNews = zlNews;
    }

    /**
     * 酒店公告信息
     */
    private List<ZlNews> zlNews;

}
